### ISSUE TITLE
Optionally ignore some E2E test failures to let new tests bake

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#103]
See kubeflow/kubeflow#558
When adding a new E2E test we might want to turn it on but not mark failures as blocking/failures because we want to bake the test before making it blocking.

We could do this as follows

1. in prow_config.yaml add options to indicate a workflow shouldn't be counted as a failure
1. If a workflow as marked as ignore don't take it into account when 
   - Marking the prow job as success or failed
   - Setting the exit code of the prow job

The JUnit XML files could still indicate whether the test passed or not so that in test grid we could see whether the test was reliable or not.

**Comment by lluunn** [comment]
It's not easy to tell whether a failure in junit file should be ignore or not.

**Comment by jlewi** [comment]
Why does that matter? We only want the ignore to apply to the GitHub status check that prow reports so that we can mark a test as not blocking merges.

The GitHub status check is based on the exit code which we compute in run_e2e_workflow.py based on

- Did argo workflows succeed
- Were there any junit files with failures

So our config file would just have to allow us to ignore an argo workflow and junit file when computing the exit code. 

Might be nice if we could put some metadata into junit files that would specify which workflow generated them.

**Comment by lluunn** [comment]
Yes we need that metadata to tell whether a junit file can be ignored.
