### ISSUE TITLE
How do we test our UI's

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#13]
We need to figure out how to test our UIs like the TFJobs UI.

**Comment by Jimexist** [comment]
by how did you mean:
- which tool
- which environment
- whether to use real backend or not

**Comment by jlewi** [comment]
I meant how do we write an automated test that drive a UI and verify it works as expected?

E.g for the TFJobs UI how do we verify that the visual output shows up as expected, that when you click on objects links work as expected etc...

**Comment by Jimexist** [comment]
I only know:

- https://github.com/segmentio/nightmare
- https://github.com/segmentio/daydream

but probably should try out https://github.com/GoogleChrome/puppeteer
