### ISSUE TITLE
Run E2E tests selectively based on modified source files

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#150]
I think we'd like to be able to trigger certain E2E workflows only when certain files are changed.

Example, if we have an E2E test for TFServing, we should only need to run that in presubmit/postsubmits if a subset of code actually changed.

One proposal is in prow_config.xml, for every workflow we could specify include/exclude expressions and we would only run a test if the files modified matched that expression.

I think this will become important as we add more tests.

**Comment by jlewi** [comment]
Bumping to P1 because test flakes are becoming a major headache. Being able to selectively run tests should help.

I think we can do something like add includes and excludes sections to each workflow in prow_config.yaml. These could be regexes or globs used to match paths.

**Comment by jlewi** [comment]
@richardsliu Any interest in taking a stab at this?

**Comment by richardsliu** [comment]
Sure, I can take a look.
