### ISSUE TITLE
Setup test infrastructure for kubeflow.org

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#18]
We want to move our test infrastructure into kubeflow.org and share it with other members of the community willing to take on responsibility for maintaining it. 

Here's what we need 

- [X] Create a GCP project kubeflow-testing in kubeflow.org
  - We'll use this for GCR and our E2E tests.
  - Created project kubeflow-ci   
- [X] Create a Google group in kubeflow.org for owners/maintainers of the test infrastructure
  - Created group ci-team@
- [X] Identify some folks to be responsible for the infrastructure and add them to the group.
- [X] Follow these [instructions](https://github.com/kubeflow/testing#setting-up-kubeflow-test-infrastructure) to setup our K8s cluster in kubeflow-testing
- [X] Update our E2E workflows to use the new cluster

**Comment by jlewi** [comment]
I added the following service accounts to project kubeflow-ci 

```
kubekins@kubernetes-jenkins.iam.gserviceaccount.com
pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
```

I think these are the service accounts used by prow jobs.

I gave them the following IAM roles
 
  - Storage Object Viewer - So they can pull the containers used for our prow jobs
  - Kubernetes Engine Developer - So they can launch Argo workflows in our K8s clusters.

**Comment by jlewi** [comment]
kubernetes testing team informed me that the only service account used is

```
pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
```

So I removed the other one.

**Comment by jlewi** [comment]
The actual service account used by prow is:

```
688881552167-compute@developer.gserviceaccount.com
```

The service account 

```
pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
```

is not used in our case so I removed it.

**Comment by jlewi** [comment]
@lluunn Is working on setting up a K8s cluster in project kubeflow-ci. Lunkai what's the status of that?

**Comment by lluunn** [comment]
Setting up the cluster now.

Some note (will update later):
PROJECT=kubeflow-ci
ZONE=us-east1-d
CLUSTER=kubeflow-testing
NAMESPACE=kubeflow-test-infra
SERVICE_ACCOUNT=kubeflow-testing

secret created: kubeflow-testing-credentials & github-token

NFS server: kubeflow-test

**Comment by jlewi** [comment]
I think the only remaining work is to update our E2E tests to start using this project. 
We might need to give our service account access to the bucket.

**Comment by lluunn** [comment]
It's currently failing with:
 python -m kubeflow.testing.run_e2e_workflow --project=kubeflow-ci --zone=us-east1-d --cluster=kubeflow-testing --bucket=kubernetes-jenkins --config_file=/src/kubeflow/tf-operator/prow_config.yaml --repos_dir=/src
INFO|2018-03-12T19:50:48|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|255| Logging to /tmp/tmpRunE2eWorkflow96wvsHlog
INFO|2018-03-12T19:50:49|/src/kubeflow/testing/py/kubeflow/testing/util.py|508| Writing gs://kubernetes-jenkins/pr-logs/pull/kubeflow_tf-operator/459/kubeflow-tf-operator-presubmit/178/started.json
INFO|2018-03-12T19:50:49|/src/kubeflow/testing/py/kubeflow/testing/util.py|495| GOOGLE_APPLICATION_CREDENTIALS is set; configuring gcloud to use service account.
INFO|2018-03-12T19:50:49|/src/kubeflow/testing/py/kubeflow/testing/util.py|37| Running: gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json 
cwd=None
INFO|2018-03-12T19:50:50|/src/kubeflow/testing/py/kubeflow/testing/util.py|69| Subprocess output:
Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]

INFO|2018-03-12T19:50:50|/src/kubeflow/testing/py/kubeflow/testing/util.py|242| Configuring kubectl
INFO|2018-03-12T19:50:50|/src/kubeflow/testing/py/kubeflow/testing/util.py|37| Running: gcloud --project=kubeflow-ci container clusters --zone=us-east1-d get-credentials kubeflow-testing 
cwd=None
INFO|2018-03-12T19:50:51|/src/kubeflow/testing/py/kubeflow/testing/util.py|69| Subprocess output:
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get" permission for "projects/kubeflow-ci/zones/us-east1-d/clusters/kubeflow-testing".

**Comment by lluunn** [comment]
Seems like pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com is the service account. Adding it back

**Comment by lluunn** [comment]
Now the error is:
kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com does not have storage.objects.create access to kubernetes-jenkins/pr-logs/directory/kubeflow-presubmit/589.txt.

**Comment by krzyzacy** [comment]
ok, I think the right way of doing this: I think your pod already has the pr-kubekins service account credential (you can reactivate it at `GOOGLE_APPLICATION_CREDENTIALS`). Before uploading logs, you should switch to use pr-kubekins to upload logs.

**Comment by lluunn** [comment]
Ah I see, thank you

**Comment by lluunn** [comment]
Actually we don't have pr-kubekins credential in the cluster under project kubeflow-ci.
(The comment above was about granting pr-kubekins service account access to kubeflow-ci)

So can we get pr-kubekins credentials? Or should we upload to our own bucket? Or maybe you can grant kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com access to kube-jenkins for now?
What's the recommended approach? @krzyzacy

**Comment by krzyzacy** [comment]
@lluunn the credential is binded in your CI Kubernetes Pod, pr-kubekins doesn't need to access kubeflow-ci, it has access to write to kubernetes-jenkins bucket, whenever you are ready to upload artifacts there.

**Comment by lluunn** [comment]
We actually have two clusters here: the first one (cluster A) is under your kubernetes infra, which has pr-kubefins. Cluster A will launch a workflow in our cluster B under project kubeflow-ci (that's why we granted pr-kubekins permission to kubeflow-ci ). Cluster B does the  real work and needs to write to kubernetes-jenkins, but it doesn't have access now.

**Comment by krzyzacy** [comment]
@lluunn ahh.. right, I forgot about that. Shall I remove kubeflow-testing@mlkube-testing.iam.gserviceaccount.com?

**Comment by lluunn** [comment]
Can we do that after we migrate everything to kubeflow-ci and make sure it's passing?

**Comment by krzyzacy** [comment]
ok, added kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com

**Comment by lluunn** [comment]
So kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com  will have access to kuternetes-jenkins?

**Comment by lluunn** [comment]
Cool thanks!

**Comment by lluunn** [comment]
The NFS server was in a different zone from the k8s cluster. I deployed a new one in the same zone:
kubeflow-test-nfs

**Comment by lluunn** [comment]
Test is now running in kubeflow-ci.
kubeflow/kubefow should pass now.
kubeflow/tf-operator is waiting for https://github.com/kubeflow/tf-operator/pull/459

**Comment by lluunn** [comment]
TODO: update the argo ui to point to the new cluster

**Comment by jlewi** [comment]
I updated testing-argo.kubeflow.org to point to: 35.227.214.243
Old ip was 35.190.88.165

**Comment by jlewi** [comment]
kubeflow-ci is setup.
Need to migrate some of the repos to use it.
