### ISSUE TITLE
Trigger E2E tests based on regex matching modified files

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#187]
Right now we can trigger tests only when certain directories are modified.

But we'd like to be able to scope a trigger to specific files. An example is for our E2E tests we don't want to run minikube on presubmit except in the situation where the minikube E2E workflow test was itself modified.

**Comment by richardsliu** [comment]
This might already work. The include_dirs are already in regex format and are being checked with fnmatch: https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py#L155

**Comment by jlewi** [comment]
Closing this issue.

We have the ability to selectively trigger specific workflows when certain files change. I don't think there's any more immediate work.
