### ISSUE TITLE
Build Docker images on pre/postsubmit

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#19]
We'd like to setup our infrastructure so that we can build Docker images on pre/postsubmit so that we always have up to date images.

Our current thinking is that we will use Argo to create pipelines that do the builds and run any tests. We can use Prow to trigger this in response to pre/postsubmit

Here's some detail how this could work

 - We modify run_workflow_e2e.py so we can easily have Prow trigger and wait for more than one Argo workflow.
 - Our workflows can take advantage of [checkout.sh](https://github.com/kubeflow/testing/blob/master/images/checkout.sh) to checkout the relevant source
     - Alternatively we could submit a single workflow with multiple sub workflows
     - I think this might entail refactoring our ksonnet definitions so that we can pull out the bits
       corresponding to the step definitions.
 - We can build and push the image
 - We can run the tests
 - If tests pass the final step can retag the image with a label like latest.

Related issues:
  - kubeflow/kubeflow#221
  - kubeflow/kubeflow#211

/cc @lluunn @yupbank

**Comment by jlewi** [comment]
Lunkai can you do this for TFServing?

I think we should go the route of structuring our workflow libsonnet file so that its easy to add the relevant template and steps from the workflow for building TFServing to our E2E workflow and just run it as a sub workflow.

**Comment by lluunn** [comment]
Sure, sounds good.

**Comment by jlewi** [comment]
@lluunn I thought about this more and realized that we can simplify our E2E tests by removing the need to build separate docker containers per repo (see #25).

As part of that I ended up adding support for running multiple workflows. This turns out to be straightforward and therefore worth doing. It gives us the flexibility of determining whether to run multiple workflows per repo or to combine workflows into a single repo.

With that change I think it will be straightforward to add the workflow you are working on to build and test the TF serving container as part of our prow jobs.

**Comment by jlewi** [comment]
#281 was merged this morning so we should now be building and testing TFServing images as part of our tests.

Lets open up more specific bugs; e.g. bugs for building our Jupyter notebooks.
