### ISSUE TITLE
Automatically build and push gcr.io/kubeflow-ci/test-worker:latest on postsubmit	

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#202]
It might be nice to use GCB to automatically build and push a new docker image on each postsubmit.

This would be a useful way to see if using GCB to build  the images is useful.

**Comment by scottilee** [comment]
@jlewi I can help with this if it's still relevant but can you give me more info on which files I need to modify?

**Comment by scottilee** [comment]
It seems like you’ve already setup some postsubmit jobs to build images in https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml — is this ticket still relevant or which ones still need postsubmit jobs?

**Comment by richardsliu** [comment]
@scottilee Those are for the kubeflow main repo. We still need one for the test-worker, which is built here: https://github.com/kubeflow/testing/tree/master/images

Right now we have to manually build and push the image whenever we make a change. We should be able to do this automatically after each postsubmit to kubeflow/testing.

**Comment by richardsliu** [comment]
Commenting just to keep this issue open.
