### ISSUE TITLE
Add argo status link to GitHub

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#22]
Would like a link directly from a PR to the corresponding argo workflow to make debugging easier

This was originally aded in #17 but this broke things #20 and was rolled back.

The environment variable GIT_TOKEN isn't defined in the prow job. This code runs in the prow container.

We'll need to rethink how we get the GIT API token; its possible prow attaches a secret already for the API token.

Alternatively it might just be easier to see if we can set it in gubernator see #10 .

/cc @jose5918

**Comment by gaocegege** [comment]
FYI, I filed [an issue](https://github.com/argoproj/argo/issues/733) to the upstream and they recommend a new project: [argo-ci](https://github.com/argoproj/argo-ci), which is built on argo for CI.

**Comment by jlewi** [comment]
What would argo-ci give us over prow?

**Comment by gaocegege** [comment]
@jlewi They said argo-ci supports status link internally compared to argo.

**Comment by jlewi** [comment]
If we use our build cluster with prow (#32) we can easily add whatever secrets we need.

@gaocegege I think argo-ci provides overlapping functionality with the dashboards and reporting in prow; but prow is more mature and battle tested by Kubernetes.
