### ISSUE TITLE
Workflows failing with "find objects: revendoring packages for environment"

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/testing#220]
Examples:
https://prow.k8s.io/log?job=kubeflow-periodic-release-branch&id=2

INFO|2018-09-28T03:41:43|/src/kubeflow/testing/py/kubeflow/testing/util.py|62| time="2018-09-28T03:41:43Z" level=warning msg="Versioned packages stored in unversioned paths - please run `ks upgrade` to correct."
INFO|2018-09-28T03:41:43|/src/kubeflow/testing/py/kubeflow/testing/util.py|62| level=error msg="find objects: revendoring packages for environment: kubeflow-periodic-release-branch-unittests-2-3e91: loading \"github\" package: reading package configuration from paths: /src/kubeflow/kubeflow/testing/workflows/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/parts.yaml, /src/kubeflow/kubeflow/testing/workflows/vendor/kubeflow/core/parts.yaml: open /src/kubeflow/kubeflow/testing/workflows/vendor/kubeflow/core@5c35580d76092788b089cb447be3f3097cffe60b/parts.yaml: no such file or directory"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 361, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 351, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 232, in run
    util.run(["ks", "show", env, "-c", w.component], cwd=w.app_dir)
  File "/src/kubeflow/testing/py/kubeflow/testing/util.py", line 74, in run
    " ".join(command), process.returncode), "\n".join(output))
subprocess.CalledProcessError: Command 'cmd: ks show kubeflow-periodic-release-branch-unittests-2-3e91 -c unit_tests exited with code 1' returned non-zero exit status 1

This may be an issue with ksonnet 0.12.0.

**Comment by jlewi** [comment]
See: kubeflow/kubeflow#1540

**Comment by richardsliu** [comment]
Can we make the ksonnet version an environment variable in the Dockerfile? Then we can build two versions of the test worker, say "latest" and "latest-0.12".

That way we can unblock the periodic tests, which require a newer version of the test-worker but won't work with 0.12.

**Comment by jlewi** [comment]
Why does it need to be an environment variable in the Dockerfile?
run_e2e_workflow.py can figure out which ksonnet version to use just by look at app.yaml in the app dir specified in prow_config.yaml

We can install multiple versions of ksonnet in the same Docker image e.g
ks-11
ks-12

run_e2e_workflow.py can then just use figure out which version to use.
