### ISSUE TITLE
test image build broken

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/testing#233]
How to reproduce: build image with 
```docker build --no-cache ...```

related: 
https://github.com/pypa/pipenv/issues/2924

**Comment by kunmingg** [comment]
@jlewi 
@richardsliu

**Comment by richardsliu** [comment]
Did you try the workaround mentioned in the link?

**Comment by kunmingg** [comment]
Doesn't work

**Comment by kunmingg** [comment]
@jlewi 
@r2d4
