### ISSUE TITLE
Periodically clean up /mnt/test-data-volume

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/testing#243]
We should clean up /mnt/test-data-volume periodically (say weekly). Otherwise the share can be out of space and block all presubmits.

**Comment by scottilee** [comment]
@richardsliu is this still relevant? If so, could you give me more background info on the script and where it should be placed?

**Comment by richardsliu** [comment]
@scottilee We're using these instructions here: https://github.com/kubeflow/testing/blob/master/playbook.md#nfs-volume-is-out-of-disk-space

We recently recreated the volume with much larger storage, so this issue is low in priority.

**Comment by scottilee** [comment]
@richardsliu does this overlap https://github.com/kubeflow/testing/issues/379? Just wondering if we can kill two birds with one stone.

**Comment by richardsliu** [comment]
Looks the same to me

**Comment by scottilee** [comment]
@richardsliu I'm still trying to figure out how this stuff works.
1. Just out of curiosity, how often does https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cleanup_ci.py run and where does it run?
2. I don't even know if this is possible, but would a good approach be to use the Python client to exec into the debug worker and execute the commands to delete the old directory? It seems like deleting and recreating the PVs would be really complicated.
3. How would I test whatever I come up with?

**Comment by richardsliu** [comment]
@scottilee I think right now we just run the script manually when we need to. When the volume gets filled up, deleting the older files might take a long time, so recreating the PV is sometimes much quicker.

Since we already have a workaround for this issue, I think it is low in priority.

**Comment by richardsliu** [comment]
Reopening this issue.
