### ISSUE TITLE
Getting a Power CI for Kubeflow

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/testing#247]
We want to enable Kubeflow running on POWER, so it is better to enable POWER CI for Kubeflow as well.

Can anyone propose some help for how to enable this?

**Comment by jlewi** [comment]
What is POWER?

**Comment by gyliu513** [comment]
Thanks @jlewi , please refer to https://www.ibm.com/it-infrastructure/power for what is POWER.

You may also see that Kubernetes now support x86, POWER and s390x for each release, this is because now many customers are using a mixed infrastructures for their cloud, so it would be great for Kubeflow CI enable POWER support. WDYT?

**Comment by gyliu513** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#server-binaries

ppc64le is for POWER. @jlewi

**Comment by jlewi** [comment]
@gyliu513 got it so its an architecture that you want to test on.
