### ISSUE TITLE
Clean up clusters in kubeflow-dev

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#248]
Here's a list of clusters running in project

```
gcloud --project=kubeflow-dev container clusters list --format="table(name, createTime)" --sort-by=createTime
NAME         CREATE_TIME
dev-cluster  2018-03-29T01:04:33+00:00
kubeflow     2018-07-13T01:35:32+00:00
hamel        2018-07-17T18:29:41+00:00
nv-dev       2018-08-13T23:03:36+00:00
cluster-1    2018-08-16T23:24:57+00:00
inc0         2018-10-02T20:06:18+00:00
v100-gpu-2   2018-11-24T16:59:38+00:00
kf-latest    2018-12-03T19:03:21+00:00
```
I think we can delete all of these except the last two.

**Comment by inc0** [comment]
feel free to delete mine

**Comment by jlewi** [comment]
Activity logs:

https://console.cloud.google.com/home/activity?project=kubeflow-dev&organizationId=714441643818

Looks like 

kf-latest created by @richardsliu 
v100-gpu-2 created by @pdmack for RAPIDs testing

**Comment by jlewi** [comment]
Query to get activity logs for CreateCluster

```
logName="projects/kubeflow-dev/logs/cloudaudit.googleapis.com%2Factivity"
resource.type="gke_cluster"
protoPayload.methodName="google.container.v1.ClusterManager.CreateCluster" 
```

**Comment by jlewi** [comment]
```
logName="projects/kubeflow-dev/logs/cloudaudit.googleapis.com%2Factivity"
resource.type="gke_cluster"
protoPayload.methodName="google.container.v1.ClusterManager.CreateCluster" 
resource.labels.cluster_name="nv-dev"
```

nv-dev was created by an engineer at nvidia.

**Comment by pdmack** [comment]
I took down v100-gpu-2. Could spin up something similar if needed for more RAPIDS work, I'm assuming.

**Comment by jlewi** [comment]
I'm going to delete 
dev-cluster
and
kubeflow

I believe these corresponded to previous attempts to have a dev cluster at dev.kubeflow.org 
https://github.com/kubeflow/testing/tree/master/deployment

These clusters are super old at this point and dev-cluster is using a fair bit of CPU (72).

I'm using this script to delete the deployments
https://github.com/jlewi/kubeflow-dev/blob/master/kubeflow-deployments/delete_deployment.sh
