### ISSUE TITLE
Set up test infrastructure for Feast

### ISSUE THREAD

**Issue by woop** [kubeflow/testing#254]
We'd like to find out if it is possible to have a testing environment (GCP project) set up for testing [Feast](http://github.com/gojek/feast) [Kubeflow Issue #2141](https://github.com/kubeflow/kubeflow/issues/2141)

This would allow us to integrate and test Feast alongside Kubeflow and Kubernetes. As long as the GCP project exists, we should be able to deploy Prow to the environment and set it up automated tests.

**Comment by jlewi** [comment]
Created project: **kf-feast** in kubeflow.org

**Comment by jlewi** [comment]
Permissions are pending in kubeflow/internal-acls#37.
I think once that's merged we can close this issue.

@woop To the extent possible we prefer all GCP infrastructure to be managed declaratively (e.g. using Deployment Manager). So it would be great if you could check in DM configs to your repo corresponding to any infrastructure you create.

I made you an owner of the project. If you need to change the IAM policy its best to update that in the YAML file defined in kubeflow/internal-acls#37 as well. We consider the YAML file to be the source of truth.

**Comment by woop** [comment]
> Permissions are pending in [kubeflow/internal-acls#37](https://github.com/kubeflow/internal-acls/pull/37).
> I think once that's merged we can close this issue.

Noted.

> @woop To the extent possible we prefer all GCP infrastructure to be managed declaratively (e.g. using Deployment Manager). So it would be great if you could check in DM configs to your repo corresponding to any infrastructure you create.

We currently use Terraform quite extensively. Do you have a strong preference for Deployment Manager? If it makes integration easier then we can pick it up.

> I made you an owner of the project. If you need to change the IAM policy its best to update that in the YAML file defined in [kubeflow/internal-acls#37](https://github.com/kubeflow/internal-acls/pull/37) as well. We consider the YAML file to be the source of truth.

Noted. Thanks!
