### ISSUE TITLE
Make it easy to run E2E Argo workflows on developers cluster; run E2E locally

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#259]
It would be very convenient if we could make it easy for contributors to spin up their own K8s cluster and run the E2E test workflows on it.

Ideally they'd be able to do this if they have

1. A K8s cluster
1. Argo deployed
1. A PVC for a read/write many volume

I think the main barriers to this are making it easy run the Argo workflows outside of prow

1. #257 will move prow artifact management out of the individual workflows and into run_e2e_workflow.py

   * This should eliminate the need to have any PROW related steps in an Argo workflow which should make it easy to run on other K8s clusters.

1. We should provide deployment manager and ksonnet configs to make it easy to deploy a new instance of a test cluster

    * This would be useful for our own purposes.

Marking this P1 because I think if we can make it easier to run/debug tests we can get folks to write more tests.

**Comment by jlewi** [comment]
@krishnadurai @swiftdiaries I think I recall one of you mentioning that you were looking at creating a better experience for running tests locally using kind. Is that accurate?

**Comment by swiftdiaries** [comment]
https://github.com/marketplace/actions/kubeflow-for-ci-cd
Created a GitHub Action for local CI with KinD. We can add tests as a separate GitHub Actions (subsequent steps)
