### ISSUE TITLE
Monitor cron jobs; dashboards?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#267]
We'd like to use cron jobs to do things like cleanup old test resources.

We need a good way to monitor them so we can see whether they are failing or succeeding.

Some features we'd like

1. Dashboard to easily view successful and failed runs.
1. Easy links to logs

Some ideas

1. Use gubernator/prow?
1. Use prometheus and stackdriver?
1. Create a custom dashboard?

**Comment by jlewi** [comment]
Bump to P1.

I think this would have high impact because it would ultimately help us reduce toil because we could identify flaky cron jobs and fix them.

For example, we have cron jobs to

* Regularly apply labels across all repos
* Cleanup CI project
* Auto deploy clusters

But we don't have any visibility into whether they are actually succeeding.

**Comment by jlewi** [comment]
Another option would be to leverage Kubeflow pipelines. Most of our cron jobs are python scripts so to some extent they fit naturally as 1 step pipelines.

It would be a good exercise to try to convert one of our cron jobs (e.g. cleanup_ci) to a 1 step pipeline that runs regularly.

**Comment by derekhh** [comment]
> It would be a good exercise to try to convert one of our cron jobs (e.g. cleanup_ci) to a 1 step pipeline that runs regularly.

I like this idea. I can take a look but probably need more pointers :)

**Comment by ywskycn** [comment]
> Another option would be to leverage Kubeflow pipelines. Most of our cron jobs are python scripts so to some extent they fit naturally as 1 step pipelines.
> 
> It would be a good exercise to try to convert one of our cron jobs (e.g. cleanup_ci) to a 1 step pipeline that runs regularly.

We're using kfp's scheduleworkflow internally for scheduling some workflows, especially the CI and monitoring workflows.

**Comment by jlewi** [comment]
@derekhh Really appreciate you volunteering.

Here's how I might tackle this.

Create a 1 step pipeline that runs "hello world".

Then use KFP to run that regularly.

Figure out with KFP how we could report success/failure. In particular, how can report success/failure so that its easy to see all the runs of the pipeline and whether they succeeded or failed.

We can use that to asses the viability of using KFP to monitor regular runs of our batch jobs.

If we are happy with that then we can create some pipelines to run actual jobs.

Two that come to mind are

1. cleanup_ci
1. [update_job.yaml](https://github.com/kubeflow/kubeflow/blob/master/releasing/auto-update/update_job.yaml)

Once we have the pipelines we can setup clusters with KFP to run them regularly.
