### ISSUE TITLE
Argo UI not showing step logs after upgrading to v2.2.1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#284]
#283 upgraded Argo images to v2.2.1 to pull in features like the job TTL.

The Argo UI now seems to be showing a blank screen when looking at the logs.

**Comment by jlewi** [comment]
I'm seeing some JS errors


﻿
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-examples-presubmit-examples-e2e-479-051143e-1223-a8bd?tab=workflow&nodeId=kubeflow-examples-presubmit-examples-e2e-479-051143e-1223-a8bd-482224849&sidePanel=logs%3Akubeflow-examples-presubmit-examples-e2e-479-051143e-1223-a8bd-482224849%3Amain
 response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.

**Comment by jlewi** [comment]
@jessesuen Any idea?

Are UI is public so you can try it out:
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-examples-presubmit-examples-e2e-479-051143e-1223-a8bd?tab=workflow&nodeId=kubeflow-examples-presubmit-examples-e2e-479-051143e-1223-a8bd-482224849&sidePanel=logs%3Akubeflow-examples-presubmit-examples-e2e-479-051143e-1223-a8bd-482224849%3Amain

**Comment by jessesuen** [comment]
I recall there might be a UI config setting that might need to be used. @alexmt can you confirm?

**Comment by alexmt** [comment]
Hello @jlewi , looks like you are seeing an issue which was fixed by https://github.com/argoproj/argo-ui/commit/37808b1b775f986744f9d34de5fe60c14d00c7fa .  Unfortunatelly fix is not released yet.  As workaround you might use a pre-release image `argoproj/argoui:v2.2.1-37808b1` .

**Comment by jlewi** [comment]
@alexmt Thanks. That should work for us.

**Comment by jlewi** [comment]
Just upgraded to argoproj/argoui:v2.2.1-37808b1 looks like the logs will now show up but seems to be a bit of a delay compared to before.

**Comment by jlewi** [comment]
We seem to be having trouble again showing logs in Argo UI; even though we are using: image
argoproj/argoui:v2.2.1-37808b1

**Comment by jlewi** [comment]
It looks like this is the latest argo image
https://hub.docker.com/r/argoproj/argoui/tags

**Comment by jlewi** [comment]
I'm seeing some 502's in JS

```
Request URL: http://testing-argo.kubeflow.org/api/logs/kubeflow-test-infra/kubeflow-presubmit-kfctl-2674-31aa10e-6245-27b6/kubeflow-presubmit-kfctl-2674-31aa10e-6245-27b6-2743090063/main
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 35.190.53.122:80
Referrer Policy: no-referrer-when-downgrade
```

**Comment by jlewi** [comment]
Looks like the pod doesn't exist so it could just be a case of the pod no longer existing in stackdriver.

```
kubectl logs kubeflow-presubmit-kfctl-2674-31aa10e-6245-27b6-2743090063
Error from server (NotFound): pods "kubeflow-presubmit-kfctl-2674-31aa10e-6245-27b6-2743090063" not found
```
