### ISSUE TITLE
Add stackdriver link to prow metadata

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#292]
We should add a link to stackdriver logs in the prow metadata.

The link should redirect to the stackdriver query to filter logs based on the pod labels identifying the workflow.
https://github.com/kubeflow/testing#argo-spec

For the link to work we will need to upgrade logging in our test cluster to use the new stackdriver agents.

**Comment by scottilee** [comment]
@jlewi Is this still relevant? If so, we should re-open it and remove the lifecycle/stale label.
