### ISSUE TITLE
Testgrid issue

### ISSUE THREAD

**Issue by lluunn** [kubeflow/testing#301]
I was looking at https://github.com/kubeflow/kubeflow/issues/2364, about why deployapp is not running periodically: https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master

It turns out it's running: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/kubeflow-periodic-master/718, and failing.

So the problems are:
1. some test is being run, but no shown on testgrid
1. fix the test
1. (minor) I think we should have better name to understand which test is from which workflow. E.g. I can't tell which workflow is running deploy-kubeflow-deploy_argo-test-argo-deploy.

cc @jlewi

**Comment by lluunn** [comment]
@jlewi Do you know how are the names on testgrid determined?

**Comment by lluunn** [comment]
Also for the kfctl workflow: 
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-periodic-master-kfctl-761-e1d0?tab=workflow&nodeId=kubeflow-periodic-master-kfctl-761-e1d0-2475545059

test-argo-deploy failed, but shown succeeded on the testgrid

**Comment by lluunn** [comment]
Another issue:
I *think* kfctl and kfctl-beta use the same artifacts name, and thus are overwriting each other,
because the testgrid should've shown two copies of each test.

cc @jlewi @kunmingg

**Comment by jlewi** [comment]
@lluunn is this resolved can we close out this issue?
