### ISSUE TITLE
Upload workflow YAML specs as prow artifacts

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#331]
It would be valuable to upload the Argo YAML spec/status as prow artifacts. This way they would be readily available.

From the YAMl spec users can get the pod id for each step which allows them to fetch the logs from stackdriver.

**Comment by jlewi** [comment]
Here are some pointers.

The code which runs the workflows is here:
https://github.com/kubeflow/testing/blob/e08595f1515fbddb2788e19b81471faf7230f4e4/py/kubeflow/testing/run_e2e_workflow.py#L273

We have a list of python dictionaries describing each workflow. So we just need to write those specs to GCS. We can do that by just writing them to GCS by calling `util.upload_to_gcs`
https://github.com/kubeflow/testing/blob/e08595f1515fbddb2788e19b81471faf7230f4e4/py/kubeflow/testing/util.py#L647

**Comment by derekhh** [comment]
I can take a look :)

**Comment by jlewi** [comment]
@derekhh Any progress on this?

**Comment by derekhh** [comment]
@jlewi Yeah I took a look and should be able to open a PR soon.

**Comment by jlewi** [comment]
Fixed by #360.
