### ISSUE TITLE
Load Testing Results into BigQuery: Use Kettle?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#335]
We'd like to load our test results into BigQuery so we can run queries to do things like identify flaky tests.

It looks like PROW has a component called Kettle to do this.
https://github.com/kubernetes/test-infra/tree/master/kettle

According to the docs for PROW the results should already be loaded into BigQuery.

When I tried to access the dataset I got an error so we should investigate further.

/cc @zabbasi

**Comment by zabbasi** [comment]
> We'd like to load our test results into BigQuery so we can run queries to do things like identify flaky tests.
> 
> It looks like PROW has a component called Kettle to do this.
> https://github.com/kubernetes/test-infra/tree/master/kettle
> 
> According to the docs for PROW the results should already be loaded into BigQuery.
> 
> When I tried to access the dataset I got an error so we should investigate further.
> 
> /cc @zabbasi 
queried  `k8s-gubernator.build.all`. it has our required data (run query in the new bigquery ui https://pantheon.corp.google.com/bigquery?utm_source=bqui&utm_medium=link&utm_campaign=classic&project=a11y-testing)

**Comment by zabbasi** [comment]
> We'd like to load our test results into BigQuery so we can run queries to do things like identify flaky tests.
> 
> It looks like PROW has a component called Kettle to do this.
> https://github.com/kubernetes/test-infra/tree/master/kettle
> 
> According to the docs for PROW the results should already be loaded into BigQuery.
> 
> When I tried to access the dataset I got an error so we should investigate further.
> 
> /cc @zabbasi

ueried k8s-gubernator.build.all. it has our required data (run query in the new bigquery ui https://pantheon.corp.google.com/bigquery?utm_source=bqui&utm_medium=link&utm_campaign=classic&project=a11y-testing)

**Comment by jlewi** [comment]
This is great.

Can we use it to compute metrics about test flakiness?

I'd like to know how often for a given commit on a PR tests failed on some but not all runs of that test for that commit.
