### ISSUE TITLE
clean up ci not clean up compute engine resources

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/testing#361]
cleanup-ci only cleans up health check resources for compute engine.  We have a much larger extent of resource leak.  Please take a look at this image:
![graph](https://storage.googleapis.com/static.ianlewis.org/prod/img/750/gcp-lb-objects2.png)

Basically we need to clean up orphaned resources plus resources associated with presubmit tests which lasted longer than a given amount of time.

This is my WIP codes for garbage collection, someone could start with it and finish it: [link](https://github.com/gabrielwen/testing/blob/garbage-collection-demo/py/kubeflow/testing/cleanup_ig.py)

Note [here](https://github.com/gabrielwen/testing/blob/fd202a547b62689fed45e4ded2bd51676abc28ab/py/kubeflow/testing/cleanup_ig.py#L31) how I use endpoint name to determine if a resource is bound to presubmit tests.  Also, this script still has a lot to improve, such as finding orphaned resources.

**Comment by lluunn** [comment]
cc

**Comment by lluunn** [comment]
also need to cleanup project kubeflow-ci-deployment

**Comment by jlewi** [comment]
Can you provide examples of the leaked resources? 

Any idea how we are leaking instance groups? All of our instance groups should be associated with GKE clusters. So if we're leaking instance groups that suggests deleting GKE cluster isn't deleting the associated instance group.

**Comment by jlewi** [comment]
Attached are list of the current instance groups and clusters in project kubeflow-ci-deployment

A lot of the instance groups have size zero.

The instance groups don't look to be named after our E2E test clusters; e.g.

```
k8s-ig--f16b03f306d1329d
```

Some of them appear to be in use by forwarding rules. 

One hypothesis is that these are node pools provisioned by auto-provisioning and that might explain why they aren't garbage collected.

[clusters.list.txt](https://github.com/kubeflow/testing/files/3098082/clusters.list.txt)
[instance_groups.list.txt](https://github.com/kubeflow/testing/files/3098083/instance_groups.list.txt)

**Comment by jlewi** [comment]
Here are the stackdriver logs for one instance group. It was created by the GKE service account.


[gce_instance_group_instance_group_id_1008177806084829541_instance_group_name_k8s-ig--53fc5e0363ccb918__logs__2019-04-18T10-29.csv.txt](https://github.com/kubeflow/testing/files/3098110/gce_instance_group_instance_group_id_1008177806084829541_instance_group_name_k8s-ig--53fc5e0363ccb918__logs__2019-04-18T10-29.csv.txt)

**Comment by jlewi** [comment]
None of these have instance templates which is very strange.

**Comment by jlewi** [comment]
Here's an instance group that is currently in use

```
```

**Comment by jlewi** [comment]
It looks like the instance group deletion might be related to ingress not doing GC kubernetes/ingress-gce#136

I think there are a couple ways to improve the situation

1. We should update cleanup_ci to use kfctl to issue a delete
1. We should update kfctl to delete the ingress explicitly and wait for it to be deleted before deleting the cluster.

**Comment by gabrielwen** [comment]
Let's take [this](https://pantheon.corp.google.com/net-services/loadbalancing/details/http/k8s-um-kubeflow-envoy-ingress--31521c72da22c515?project=kubeflow-ci-deployment&tab=details) URL mapping as example:
- URL mapping: `k8s-um-kubeflow-envoy-ingress--31521c72da22c515`
- Associated target proxy: `k8s-tp-kubeflow-envoy-ingress--31521c72da22c515`
- Associated forwarding rule: `k8s-fw-kubeflow-envoy-ingress--31521c72da22c515`
- Health checks/backend services:
  - `k8s-be-30493--31521c72da22c515`
  - `k8s-be-32218--31521c72da22c515`
  - `k8s-be-32285--31521c72da22c515`
- Associated instance group: `k8s-ig--31521c72da22c515`

**Comment by zhenghuiwang** [comment]
Thanks for the investigation @jlewi ! 

> 1. We should update cleanup_ci to use kfctl to issue a delete
> 2. We should update kfctl to delete the ingress explicitly and wait for it to be deleted before deleting the cluster.

Just to make sure I understand it. Do we need to finish task 2 first? Without 2, the issued kfctl delete may still leak resources if ingress doesn't finish its GC.

**Comment by jlewi** [comment]
@zhenghuiwang Yes I think that's correct; we will need kfctl to delete the namespace and/or ingress first and wait for it to be deleted.

It looks like `kfctl delete` does delete the namespace
https://github.com/kubeflow/kubeflow/blob/0c410b78953f306dc58a2f024cb5fa89487d98dd/bootstrap/pkg/kfapp/ksonnet/ksonnet.go#L286

But it doesn't look like we wait for the namespace to be deleted. So we might need to file an issue to fix that.

/cc @gabrielwen @kkasravi

**Comment by jlewi** [comment]
@zhenghuiwang Any progress on this?

**Comment by gabrielwen** [comment]
FYI we have resource pressure on `kubflow-ci-deployment` again.

**Comment by jlewi** [comment]
Looks like #390 was just opened to fix this.
