### ISSUE TITLE
junit files from multiple runs of a workflow with different parameters clobber each other

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#372]
Right now we run our E2E test workflows with different parameters (e.g. the kfctl_e2e_workflow).

But the junit files are often times not unique. As a result we end up clobbering the runs.

Example:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1121841104535162880/

We have two different workflows
/mnt/test-data-volume/kubeflow-postsubmit-kfctl-go-iap-97ce5be-2880-8b97/output/artifacts/junit_kfctl-go-delete-test.xml 
/mnt/test-data-volume/kubeflow-postsubmit-kfctl-go-iap-istio-97ce5be-2880-bc9c/output/artifacts/junit_kfctl-go-delete-test.xml

They would both be uploaded to the same location. 

Except in this case copy-artifacts never ran.
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-postsubmit-kfctl-go-iap-istio-97ce5be-2880-bc9c?tab=workflow&nodeId=kubeflow-postsubmit-kfctl-go-iap-istio-97ce5be-2880-bc9c-605660832

/cc @zabbasi

**Comment by jlewi** [comment]
Possible solutions

1. One possible solution would be to use run_workflow.py to copy the artifacts and add some unique salt to each file based on workflow. (see also #257)

1. If prow supports subdirectories for junit we could give each workflow its own subdirectory for junit files

I think we should investigate the second option; to see if gubernator supports it or if not how hard it would be to support it.

**Comment by jlewi** [comment]
@zabbasi Any update on this?

**Comment by jlewi** [comment]
I think @zabbasi tried this in #3381. When we looked at the prow/gubernator code it looked like junit files might not be pulled from subdirectories. I think prow/gubernator has a recursive setting that isn't currently set.

@zabbasi Could you update this issue please with the relevant links?

#3381 tried to use subdirectories but it was hard to tell whether it was working because some of the tests were not writing to subdirectories so it was hard to confirm that the tests using subdirectories were actually reporting their results.

I suggested trying it out in a repository with a fewer number of tests e.g. kubeflow/testing. Update all the tests to report tests in a subdirectory. That way if any results are reported in prow we know its pulling from subdirectories.

**Comment by zabbasi** [comment]
As suggested by @jlewi I updated [this wip pr](https://github.com/kubeflow/kubeflow/pull/3381) to use subfolder for all workflow tests. It turns out that the gubernator does not pull and list the junits if they are located in subdirectories. However still the tests are available in testgrid and the xml files are available in Artifacts (the link is provided by gubernator).

**Comment by jlewi** [comment]
Repasting @zabbasi's notes

Here are some notes:
- Prow supports having junit xml files in subdirectories and it will upload everything in the $ARTIFACTS directory. Prow does not write junit, that is the responsibility of the tests. Junit (and all other files) in the $ARTIFACTS directory are uploaded by the sidecar pod utility: https://github.com/kubernetes/test-infra/tree/master/prow/sidecar

- TestGrid reads any nested folders in $Artifacts 

- gubernator has the ability to read nested folders in $Artifact, however the running instance is currently configured with flag `recursive=false` which means that it does not read junits if they are stored in subfolders. 
  -- https://github.com/kubernetes/test-infra/blob/master/gubernator/view_build.py#L150
  -- https://github.com/kubernetes/test-infra/blob/master/gubernator/config.yaml#L42

**Comment by jlewi** [comment]
Opened kubernetes/test-infra/issues#13525

We should see what they say and then decide how to proceed.

**Comment by jlewi** [comment]
Chatted with some folks from the engprod team.

This should be supported in spyglass today.
https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L37

The current config should match regexes.

So under the current configuration, I'm pretty sure artifacts/junit/anything/anything.xml would also match
as would artifacts/junit_anything/anything.xml

We will try that and see if it works.

**Comment by jlewi** [comment]
Next steps; I think we want to resurrect the test PR from @zabbasi and try it using one of the prefixes mentioned above e.g.

```
artifacts/junit/${test_name}/
```
@derekhh any interest in trying this out?

**Comment by derekhh** [comment]
@jlewi Sure I can take a look :)
