### ISSUE TITLE
Any one can help to release new image for test-worker

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#373]
In the PR #370 , updated Dockerfile to install kustomize, but no new image for `gcr.io/kubeflow-ci/test-worker/test-worker` is pushed, anyone in team can help to publish one image for test-worker? Seem I have no permission to do that. Thanks!

/cc @kunmingg @lluunn

**Comment by jlewi** [comment]
Do we build the image on post-submit? 

I think we should automate the building of the test worker image. We generally do that by creating a post submit job that will build and push the image to the appropriate repository.
