### ISSUE TITLE
Do shallow clones of Kubeflow repos in checkout.sh

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#380]
We clone Kubeflow repos in these scripts
https://github.com/kubeflow/testing/blob/665fda22af4aa72639efdfd62a4fe2e440cfad7b/images/checkout.sh#L28

https://github.com/kubeflow/testing/blob/665fda22af4aa72639efdfd62a4fe2e440cfad7b/images/checkout_repos.sh#L82

Right now we are cloning the entire history which uses a lot of space.

Doing

```
git clone --depth=1 git@github.com:kubeflow/kubeflow.git 
```

Appears to cut the size from 286 M to 150M

**Comment by scottilee** [comment]
@jlewi looks like this was taken care of with `--depth=2` on both files.

/close
