### ISSUE TITLE
junit test failures not accounted for in github status

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#412]
Prow only uses the exit code of the prow job to determine whether to report success or failure to GitHub.

Right now that doesn't take into account junit results. So we need to update our job to exit with non-negative exit code if some of the junit files report failures.

/cc @derekhh

**Comment by derekhh** [comment]
Ah - I guess this should be an easy fix. I'll take a look this week.

**Comment by jlewi** [comment]
Thank you so much @derekhh

**Comment by derekhh** [comment]
@jlewi - I might be missing something but it seems currently we do rely on JUnit results as well?

https://github.com/kubeflow/testing/blob/2cc1bfbdd6c8e74e7561c2660910d005210b468d/py/kubeflow/testing/prow_artifacts.py#L245

Let me know if my understanding is incorrect. Thanks!

**Comment by derekhh** [comment]
@jlewi Gentle ping

**Comment by jlewi** [comment]
@derekhh good point. If I recall correctly I filed this issue because I observed a prow job that reported success even though there were junit failures.

I must have been mistaken; or something else must have been going on.

**Comment by derekhh** [comment]
Copying the Slack conversation here so we can track it:

```
Jeremy Lewi  4 hours ago
Are there any edge cases where that field might not get checked?

Jeremy Lewi  4 hours ago
I thought I filed the issue because I saw test reported as success even though there were junit failures

Jeremy Lewi  4 hours ago
Maybe there was something else going on.

Richard Liu  3 hours ago
Sometimes Prow itself does not report status correctly to Github

Richard Liu  3 hours ago
There's some status json file that we write, at the end of the test

Richard Liu  3 hours ago
And if that file fails to write, the status shows up as pending or something

Jeremy Lewi  3 hours ago
Thanks I think we can close the issue.
```

**Comment by jlewi** [comment]
Reopening because I'm observing junit failures not reported as a status check failure.
Here's a presubmit run where we have a junit failure
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/4129/kubeflow-presubmit/1173794332621148160/

The GitHub status check however indicates the tests passed (this is how the code that broke the tests kubeflow/kubeflow#4114) ended up getting merged.

The status is reported as success. So I think there must be a bug in the logic in check_no_errors that checks the junit files.
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/prow_artifacts.py#L245

Here's the junit file
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/4129/kubeflow-presubmit/1173794332621148160/artifacts/junit_go-kfctl-unit-tests.xml

The junit file shows that it reports a failure.

We should be logging a message that we are checking each junit file.
https://github.com/kubeflow/testing/blob/c43837c57b52399056863d9c3354eaadee7647df/py/kubeflow/testing/prow_artifacts.py#L208

I don't see those messages in the logs
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/4129/kubeflow-presubmit/1173794332621148160/build-log.txt

So my suspicion is that there is a bug in the logic to list the junit files and we end up not returning any junit files.

@derekhh @scottilee any interest in looking into this?

**Comment by derekhh** [comment]
@jlewi Sure I'll take a look - that does seem weird
