### ISSUE TITLE
release infra broken.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/testing#415]
Currently for each of 
https://github.com/kubeflow/katib
https://github.com/kubeflow/tf-operator
https://github.com/kubeflow/pytorch-operator
we use same workflow for both test and release.

Recently test workflows are updated together with test infra.

We need to update release infra as well otherwise release workflow will not work.

**Comment by scottilee** [comment]
@kunmingg can you close this ticket?

**Comment by jlewi** [comment]
I don't think this is fixed. We probably need to go about figuring out how we want the release infra should be set up and set it up.
