### ISSUE TITLE
checkout.sh shouldn't require PROW environment variables

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#42]
[checkout.sh](https://github.com/kubeflow/testing/blob/master/images/checkout.sh) supports the PROW environment variables.

But it also supports the more convenient syntax we introduced to specify for extra repos.

For workflows triggered outside of prow (e.g. manually) its more convenient just to specify EXTRA_REPOS.

We should update checkout.sh so that it doesn't assume REPO_OWNER and other prow environment variables.

**Comment by scottilee** [comment]
@jlewi can you provide more info about which vars are prow env vars (is that listed somwhere?) and what the more convenient syntax is? It's not clear what needs to be replaced.

**Comment by derekhh** [comment]
@scottilee I might be wrong but I think this is the list: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables

**Comment by scottilee** [comment]
@derekhh Thanks!

@jlewi what is the more convenient syntax you referred to other than EXTRA_REPOS? Is there a list somewhere?

**Comment by jlewi** [comment]
We have 
https://github.com/kubeflow/testing/blob/master/images/checkout_repos.sh

But I think we might want to standardize on
https://github.com/hashicorp/go-getter

I think we can close this issue.
