### ISSUE TITLE
Remove kf-v0-4-n00

### ISSUE THREAD

**Issue by scottilee** [kubeflow/testing#422]
@jlewi Per our discussion on Slack, I'm creating this issue to remove https://github.com/kubeflow/testing/tree/master/test-infra/kf-v0-4-n00. Is there anyone we should cc on this ticket before I submit a pull request?

**Comment by jlewi** [comment]
Nope just go ahead and do it.

/assign @scottilee

**Comment by scottilee** [comment]
Merged.

/close
