### ISSUE TITLE
run_e2e_workflow.py support TektonCD pipeline

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#425]
We should modify run_e2e_workflow.py so that we can also submit and run tektoncd/pipeline's and not just argo workflows.

We probably want to fork our argo_client to create a tekton client
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/argo_client.py

blocked by kubeflow/testing#423 run_e2e_workflow.py should support calling py functions to generate the workflow.

/cc @scottilee

**Comment by pdmack** [comment]
Why support multiple w/f pipeline providers in testing? Or is this a transition to ultimately replace argo?

**Comment by jlewi** [comment]
@pdmack I think we'd want to ideally standardize. Tekton has some really nice properties in terms of reusability which is why I think it might make sense to standardize on Tekton. But one of the easiest ways to evaluate it is to pick an E2E test and try it out.

**Comment by jlewi** [comment]
@gabrielwen has a PR pending for this in kubeflow/testing#/622

**Comment by jlewi** [comment]
Follow on work to #622 

1. Create a lint and/or unittest tasks and pipelineruns on Kubeflow/testing to serve as canonical example of using Tekton for CI/CD
1. Setup ACM to sync Tekton tasks to the CI cluster

**Comment by NikeNano** [comment]
@jlewi how is this progressing? As I understand everything is set up for using tekton for the testing of e2e now is that correct? I am asking in relation to : https://github.com/kubeflow/mpi-operator/pull/244 in order to run a notebook example as e2e test for the mpi operator.

**Comment by jlewi** [comment]
@NikeNano #622 was merged but there hasn't been any testing to ensure its working. You could give it a try and see what issues you run into.

**Comment by jlewi** [comment]
@NikeNano #681 verifies that Tekton is working by adding a simple go unittest presubmit to this repo.
Reusable tekton tasks and pipelines for running notebooks are still missing.
