### ISSUE TITLE
Setup stale bot on kubeflow/testing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#427]
We just need a YAML file like this

https://github.com/kubeflow/kubeflow/blob/master/.github/stale.yml

/cc @scottilee @derekhh

**Comment by scottilee** [comment]
@jlewi is there anything you want in the config that's different from what kubeflow/kubeflow is using?

I'd assume one thing that is different is `exemptLabels` -- what do you want them to be for kubeflow/testing?

**Comment by jlewi** [comment]
I think you can just copy the config.

**Comment by derekhh** [comment]
@scottilee Feel free to assign this to yourself :)

**Comment by scottilee** [comment]
Sure.

/assign

**Comment by scottilee** [comment]
Pull request was merged.

/close
