### ISSUE TITLE
No space in the CI/CD test env

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#435]
No space in the CI/CD test env, beflow is kfserving CI/CD presubmit test:

```
fatal: could not create leading directories of '/mnt/test-data-volume/kubeflow-kfserving-presubmit-e2e-250-7dd4267-5664-a27c/src/kubeflow
/kfserving': No space left on device
```

**Comment by jlewi** [comment]
Playbook
https://github.com/kubeflow/testing/blob/master/playbook.md#nfs-volume-is-out-of-disk-space

**Comment by jlewi** [comment]
Stackdriver only shows freebytes for last 6 weeks; [link](https://app.google.stackdriver.com/metrics-explorer?isAutoRefresh=false&project=kubeflow-ci&timeSelection=%7B%22timeRange%22:%22custom%22,%22start%22:%222019-07-01T12:00:38.771Z%22,%22end%22:%222019-08-12T12:00:38.771Z%22%7D&xyChart=%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22file.googleapis.com%2Fnfs%2Fserver%2Ffree_bytes%5C%22%20resource.type%3D%5C%22filestore_instance%5C%22%22,%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22secondaryCrossSeriesReducer%22:%22REDUCE_NONE%22,%22minAlignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%5D,%22unitOverride%22:%22By%22%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D)

![free_bytes](https://user-images.githubusercontent.com/777219/62863675-5fe28680-bcbe-11e9-9bf9-48a6063a8147.png)

**Comment by jinchihe** [comment]
@jlewi Great thanks for the quickly action, Yes, that's OK now.
