### ISSUE TITLE
no results showing up in testgrid

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#438]
Our test grid is suddenly not showing any results
https://testgrid.k8s.io/sig-big-data#kubeflow-postsubmit

**Comment by jlewi** [comment]
presubmit grid for kubeflow shows some results
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-presubmit

No postsubmit results
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-postsubmit

We are running postsubmit jobs
https://prow.k8s.io/?repo=kubeflow%2Fkubeflow&type=postsubmit

Here's a postsubmit run in spyglass
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1160964583272222720/

**Comment by jlewi** [comment]
Annotation to add to testgrid-dashboards here
https://github.com/kubernetes/test-infra/blob/f651985a836637f122408fd63e6dea5b07e2aac7/config/jobs/kubeflow/kubeflow-postsubmits.yaml#L25

**Comment by jlewi** [comment]
I think something may have changed in the test grid config.

We use to have kubeflow info in testgrid/config/config.yaml
https://github.com/kubernetes/test-infra/pull/4951/files

Not seeing that in
https://github.com/kubernetes/test-infra/blob/master/config/testgrids/config.yaml


https://github.com/kubernetes/test-infra/pull/4951/files

**Comment by jlewi** [comment]
One possible fix might be to list test-groups here
https://github.com/kubernetes/test-infra/blob/99b91b56b097e39d70cb1ae82c0b1cb57d98ac48/config/testgrids/config.yaml

And explicitly specify the GCS prefix. 

It looks like we use to explicitly specify the GCS location for each test grid but now its using annotations but the implicit location may not be matching where are artifacts are stored.

**Comment by Katharine** [comment]
I added back explicit configuration in kubernetes/test-infra#13891. I think only postsubmits should've had this issue.

I think the root cause is a prow bug where it incorrectly determines where your results should be stored.

**Comment by jlewi** [comment]
Thank you!
Its working
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-postsubmit
