### ISSUE TITLE
Verify python code is formatted with yapf

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#44]
In kubeflow/tf-operator#401 we started using yapf to enforce a consistent Python style.

We should a presubmit test so that we can ensure all python code is properly formatted.

/cc @Jimexist

**Comment by scottilee** [comment]
@jlewi can this be closed? I just skimmed the pull request but it looks like yapf was added to TravisCI which is no longer used, not sure if it should be added to a Prow test or it's not relevant anymore.

**Comment by derekhh** [comment]
@scottilee @jlewi I actually do want yapf on this repo. Can we try to set this up? I can try to get this done if you both feel it's important.

**Comment by scottilee** [comment]
@derekhh go for it.
