### ISSUE TITLE
Standardize/cleanup different bug kind labels

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#440]
The following labels are currently used to indicate what kind an issue is

* community/discussion
* community/question
* kind/bug
* improvement/enhancement
* addition/feature
* kind/process

Not  using the kind prefix has a bunch of drawbacks

* Prow allows the "/kind" command to be used to set the kind.
  * We use this in our issue templates to automatically set the kind
  * If we don't use kind as a prefix people can't set it via the kind bot
* It makes our [issue triage process](https://github.com/kubeflow/community/blob/master/proposals/issue_triage.md) more complicated because we'd like to set different requirements based on the kind
   * e.g. A discussion probably doesn't need a priority or be assigned to a project

I propose we use the following kinds

* kind/bug
* kind/question
* kind/feature
* kind/discussion
* kind/process

I think we want to make the following changes

* Update [kubeflow_label.yml](https://github.com/kubeflow/testing/blob/master/label_sync/kubeflow_label.yml) 

   * Map the old times to the new types

* Update the running instance of label sync and make sure it succesfully applies across all repos
* Update the issue label bot configs ([example](https://github.com/kubeflow/kubeflow/blob/master/.github/issue_label_bot.yaml)) in all repos so that it uses the new kinds

**Comment by jlewi** [comment]
Updating label_sync might make for a good first issue; other parts will require access to test infra.

@derekhh @jian-he @scottilee

**Comment by rbrishabh** [comment]
Hey @jlewi !

I would love to to the first part of this issue as my good first issue.

I noticed that in ```label_sync``` there are no labels likes - 

```
improvement/enhancement
addition/feature
kind/process
```

Do I need to add new labels for these ones? If yes, what color should I be using?

Thanks!

**Comment by jlewi** [comment]
@rbrishabh There should be a label for each label that we want; e.g. kind/process. There shouldn't be label definitions for labels we don't want. However labels that we want to rename should be listed as previous labels

e.g. addition/feature should be listed as a previous label for kind/feature

**Comment by rbrishabh** [comment]
Alright, I'm on it! Will give a PR soon!

**Comment by rbrishabh** [comment]
Definitely! I'll get right to it @jlewi

**Comment by rbrishabh** [comment]
Hey @jlewi !

The 8 repositories where I found issue_label_bot.yaml were:

1. Kuberfolow
2. Testing
3. Website
4. Fairing
5. Examples
6. tf-operator
7. code-intelligence
8. community

There were no issue_label_bot.yaml files in the rest of the 24 repositories.
For your ease, I have tagged you on all 8 pull requests.

Let me know if I went wrong anywhere! Thanks! =)

**Comment by rbrishabh** [comment]
Whoops I think by mistake I updated cache file in this repo as well :P

**Comment by jlewi** [comment]
That sounds right.

@rbrishabh be sure to "/assign jlewi" your PRs to me so that they show up in my review queue otherwise I won't see them.

You can see my inbox here
https://k8s-gubernator.appspot.com/pr/jlewi

**Comment by rbrishabh** [comment]
I think this can now be closed ;)

**Comment by jlewi** [comment]
Thanks @rbrishabh
