### ISSUE TITLE
Setup KCC to manage kubeflow.org projects

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#457]
We are creating more and more GCP projects and GKE clusters to use for administering kubeflow.org.

In order to continue to scale and grow we need to manage this more declaratively and move to GitOps. This will eventually make it easier for Kubeflow contributors to create infrastructure they need just by submitting PRs.

The latest example is @scottilee is trying to setup infrastructure to auto-sync events to the Kubeflow calendar kubeflow/community#288.

To do that we need

1. A new GCP project or reuse an existing GCP project.
1. A GKE cluster 
1. A GCP service account

I think we should start using [GCP Cloud Connector](https://cloud.google.com/config-connector/docs/overview) to set this up.

Here's how this should work.

1. All KCC managed projects should be in the GCP folder kf-kcc
    * This folder already exists.
1. The project kf-kcc-admin is where we should create a GKE cluster with cloud connector installed
1. GCP projects created via KCC should exist in the subfolder kf-kcc-admin > users
    * This sub folder already exists as well.
1. Resources created by KCC should be checked into source control inside kubeflow/testing
1. We should create a google group in https://github.com/kubeflow/internal-acls for folks with permissions to administer/setup KCC

So first we need to setup KCC

1. Create the Google Group
1. Grant the google group appropriate permissions on the folder
1. Setup KCC in project kf-kcc-admin
     * There is already a cluster named kf-kcc in that project I think we might already have an older version of KCC installed and setup on it. 
     * We can try reusing that or starting a clean installation.

Once KCC is setup we should use it to setup the resources for the community calendar

1. Create a GCP project for community management

    * Doesn't look like KCC supports project creation so we should do that manually (GoogleCloudPlatform/k8s-config-connector#32)
1. Use KCC to create the appropriate [service account](https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/resources/iamserviceaccount) to be used to do the calendar sync.
1. Use KCC to define an IAM policy to give folks work on community maintenance access to that project (e.g. make them project editors)
1. Either use KCC to setup a GKE cluster in that project or use kfctl to deploy a KF cluster with IAP in that project
    * We should use GKE workload identity to allow processes in that cluster to authenticate as a google service account
1. Deploy the calendar sync app in that cluster

@derekhh and @scottilee Any interest in trying to take this on?

**Comment by jlewi** [comment]
@derekhh @jinchihe I have created the Google group and given you access in #147 in the hope of motivating you to help out with this :)

@scottilee I will give you access as well but I'd like to use a corporate account and not a personal account and I don't know yours.

**Comment by scottilee** [comment]
Cool, unless I'm misunderstanding it looks like Cloud Connector is infrastructure orchestration through Kubernetes manifests. If there's anything that CC doesn't support yet that you'd want managed through something like Terraform let me know because I can definitely do that.

I'm happy to help and I've messaged you to see if we can figure out how we can get me access.

**Comment by derekhh** [comment]
@jlewi Sure let me take a look.

**Comment by jlewi** [comment]
@scottilee you should have access now. For anything that KCC can't manage we should file an issue and figure out when KCC will manage it.

**Comment by scottilee** [comment]
@derekhh I'd be happy to help with this, maybe we can split up tasks (let me know if any of these are wrong):

**Config Connector**
- [ ] Upgrade the `kf-kcc` and `containercluster-sample-2` GKE clusters in the `kf-kcc-admin` project to version `1.13.7-gke.24`
- [ ] Create a PR with [Config Connector](https://cloud.google.com/config-connector/docs/overview) changes in [kubeflow/testing](https://github.com/kubeflow/testing) -- I think we should test Config Connector changes in the `containercluster-sample-2` cluster and then apply them to the `kf-kcc` cluster once the PR is approved and merged, what do you guys think?

**Community Management**
- [ ] Manually create a GCP project for community management -- call it "community-management" or "kubeflow-community"?
- [ ] KCC: create service account to do the calendar sync
- [ ] KCC: define an IAM policy to make people working on community maintenance project editors to community management project
- [ ] KCC: setup a GKE cluster in the community management project (or use kfctl to deploy a KF cluster with IAP)
- [ ] Setup [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) to allow processes in the community management cluster to authenticate as a Google service account
- [ ] Deploy the [calendar sync app](https://github.com/kubeflow/community/blob/master/scripts/calendar_import.py) into the community management cluster


Questions for @jlewi:
1. Under the `kf-kcc-admin` project I don't see any folders, even a `users` folder, is this a permission issue?
2. Is there a naming guide somewhere? For instance, how do we want to name projects, clusters, policies, etc. It will probably reduce future pain to have consistent naming schemes for resources.

**Comment by derekhh** [comment]
@scottilee Thanks for the detailed task list! Let me take a quick look at Config Connector related docs and get back to you. :)

**Comment by jlewi** [comment]
@derekhh any update on this?

**Comment by derekhh** [comment]
@jlewi Sorry I haven't found time to work on this issue last week but I'll provide some update this week for sure. :)

**Comment by scottilee** [comment]
@derekhh Any update?

**Comment by derekhh** [comment]
@scottilee - Super sorry again...I read some documentation on Config Connector but wasn't able to make actual progress. If this is an urgent task please feel free to start working on it, but if not that urgent I'm still willing to take on this and see what I can do this week.

**Comment by scottilee** [comment]
No worries, I just didn't want to step on your toes. I have some time this week so I will see if I can get started on it.

**Comment by jlewi** [comment]
@scottilee the plan you outlined above looks good to me. 

The folder structure is

kf-kcc - Folder
  users - Folder
  kf-kcc-admin - project

So there aren't any folders under kf-kcc-admin

**Comment by scottilee** [comment]
@jlewi I played around with Cloud Connector and I think I understand how it all works. I also recreated the kf-kcc cluster to version "1.14.8-gke.2" and with a newer version of the config connector.

1. You wrote above: "GCP projects created via KCC should exist in the subfolder kf-kcc-admin > users". All I see are projects like "kf-kcc-admin" and "kf-kcc-test1" in my 'Select a project' view and I don't see things at the folder level. My understanding is that it's: org -> folders -> project -> resources. Given that I am only seeing things at the project level I will have Cloud Connector create a new project called "kf-community" within the folder that the kf-kcc-admin project lives in and then within the "kf-community" project I will create a GKE cluster called "kf-community-calendar". Let me know if this all sounds okay.

2. I've created YAML files but the process of setting up Cloud Connector is more intensive. You didn't mention anything about automation but I ended up adding some bash scripts for setup, although I think something like this would be better suited for Terraform...

**Comment by jlewi** [comment]
thanks @scottilee 

It looks like the hierarchy is currently

> kf-kcc [folder
   kf-kcc-admin [project]
  > users[folder]
       > kf-kcc-test1

I think we want all kcc managed projects to be under the users folder. This way we can set permissions & policies on the users folder and have them apply to all kcc managed projects.

**Comment by scottilee** [comment]
@jlewi This is what I see (ignore the "Terraform" project, it's a personal one):

![Screen Shot 2020-02-23 at 10 54 37 PM](https://user-images.githubusercontent.com/7443383/75133423-93e82c80-568f-11ea-950a-5f19d8a60dcf.png)

I don't think I am seeing everything I am supposed to like the users folder or the kf-kcc folder, but I may be looking in the wrong place?

**Comment by jlewi** [comment]
* It looks like projects are now supported with KCC 
  * https://cloud.google.com/config-connector/docs/reference/resources#project
* It looks like @scottilee has KCC setup inkubeflow/testing#525

Some things to look at next

* Configuring ACM(https://cloud.google.com/anthos-config-management/docs)
* Creating an example of provisioning a project and cluster using KCC
