### ISSUE TITLE
ks segfaulting trying to submit workflows

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#459]
Presubmit for kubeflow/kubeflow#4097

Segfault

```
INFO|2019-09-09T17:39:32|/src/kubeflow/testing/py/kubeflow/testing/util.py|45| Running: ks env add kubeflow-presubmit-tf-notebook-release-4096-fd1d39e-4288-9b07 --namespace=kubeflow-test-infra 
cwd=/src/kubeflow/kubeflow/components/tensorflow-notebook-image/releaser
INFO|2019-09-09T17:39:32|/src/kubeflow/testing/py/kubeflow/testing/util.py|60| Subprocess output:

INFO|2019-09-09T17:39:32|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=info msg="Using context \"gke_kubeflow-ci_us-east1-d_kubeflow-testing\" from kubeconfig file \"/root/.kube/config\""
INFO|2019-09-09T17:39:32|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=info msg="Creating environment \"kubeflow-presubmit-tf-notebook-release-4096-fd1d39e-4288-9b07\" with namespace \"kubeflow-test-infra\", pointing to cluster at address \"https://35.196.213.148\""
INFO|2019-09-09T17:39:34|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| panic: runtime error: invalid memory address or nil pointer dereference
INFO|2019-09-09T17:39:34|/src/kubeflow/testing/py/kubeflow/testing/util.
```

**Comment by jlewi** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/4096/kubeflow-presubmit/1171115329498124288/

**Comment by jlewi** [comment]
Looking at gcr.io/kubeflow-ci/test-worker it looks like we recently updated the image tagged latest
v20190905-cff62af-e3b0c4

**Comment by jlewi** [comment]
The debug worker is using
    image: gcr.io/kubeflow-ci/test-worker:latest
    imageID: docker-pullable://gcr.io/kubeflow-ci/test-worker@sha256:db67f414c04a918f60aa081d9f9b85b4665c54bac1cdf706efd25a7ef63e7e29

That corresponds to the tag
v20190802-c6f9140-e3b0c4

**Comment by jlewi** [comment]
I don't see any critical fixes in 
https://github.com/kubeflow/testing/commits/master/images

So I'm going to try moving the latest tag back

**Comment by jlewi** [comment]
It looks like rolling bag the latest tag back to
v20190802-c6f9140-e3b0c4
fixed that particular issue

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/4097/kubeflow-presubmit/1171123500727930881/

So it looks like there might be some difference in the ks binary in the existing image vs. the one that would get pulled into  a new image.

**Comment by kkasravi** [comment]
That’s disconcerting especially if the is version hasn’t changed.

**Comment by jlewi** [comment]
See also ksonnet/ksonnet#883

maybe we aren't using the version of ksonnet in which it was fixed.
