### ISSUE TITLE
Allowing Public Access to CI Logs

### ISSUE THREAD

**Issue by Tabrizian** [kubeflow/testing#464]
I am a new contributor to Kubeflow, during the pull requests time is consumed because the contributor needs to wait for someone who has access to the CI logs to post them so that the contributor can read the log and fix the problem.

I was wondering is it possible to make the access to the Kubeflow logs public and/or creating a google group to grant viewer only access?

Thanks!

**Comment by jlewi** [comment]
@Tabrizian I will set up a google group. What is your Google account? Using your corporate account is preferred to your personal account.

**Comment by Tabrizian** [comment]
Here is my email address:

iman.tabrizian@gmail.com

**Comment by Tabrizian** [comment]
May I close this issue? I can see the logs in Argo.

**Comment by scottilee** [comment]
@Tabrizian please re-open if you have any further issues.
