### ISSUE TITLE
Setup kubeflow-testing to be cluster for prow jobs - move off Kubernete's prow instance

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#475]
See: GoogleCloudPlatform/oss-test-infra#93
See :kubernetes/test-infra#14343

/assign @scottilee

**Comment by jlewi** [comment]
Created namespace test-pods

```
kubectl create namespace test-pods
```

**Comment by jlewi** [comment]
Next step run mkbuild-cluster
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/mkbuild-cluster/README.md

**Comment by jlewi** [comment]
I tried runnin git and got a permission issue which I need to debug

```
INFO: Running command line: bazel-bin/prow/cmd/mkbuild-cluster/linux_amd64_stripped/mkbuild-cluster '--project=kubeflow-ci' '--zone=us-east1-d' '--cluster=kubeflow-testing' '--alias=default' --print-entry
INFO: Build completed successfully, 1 total action
ERRO[0002] Failed to validate credentials (consider --get-client-cert)  error="response has status \"403 Forbidden\" and body \"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods is forbidden: User \\\"client\\\" cannot list resource \\\"pods\\\" in API group \\\"\\\" in the namespace \\\"kube-system\\\"\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"pods\"},\"code\":403}\n\""
FATA[0002] Failed: list all pods to check new credentials: response has status "403 Forbidden" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"client\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
" 

```

**Comment by jlewi** [comment]
I had to add the --skip-option check

```
bazel run //prow/cmd/mkbuild-cluster --   -project=kubeflow-ci -zone=us-east1-d -cluster=kubeflow-testing -alias=default -print-entry -account=jlewi@google.com --skip-check > cluster.yaml
```

@scottilee  I will share the result with you.

**Comment by scottilee** [comment]
@jlewi Travis ran the following using the information in the yml file but it didn't have the required access:
```
kubectl --context=kubeflow get pods -n test-pods

Error from server (Forbidden): pods is forbidden: User "client" cannot list resource "pods" in API group "" in the namespace "test-pods"
```

**Comment by jlewi** [comment]
@scottilee Who or what is travis? Who is trying to access the cluster and how are they trying to autenticate to the cluster?

**Comment by scottilee** [comment]
Travis is @clarketm, who is helping on the migration to https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs.

He was connecting the the Kubeflow CI cluster to the GoogleCloudPlatform Prow instance using the yml file you generated. He recommends generating a cert with cluster-admin access and referenced this as a doc for cert generation: https://github.com/clarketm/kubernetes_test-infra/tree/master/pkg/gencred

**Comment by clarketm** [comment]
@scottilee @jlewi 
The provided x509 certificate does not have the required authorization to administer pods in your build cluster. This can be fixed using the following reference: 
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/mkbuild-cluster/README.md#credential-errors

**Comment by jlewi** [comment]
@clarketm Thanks. Is it possible to use GCP IAM instead of x509 certificates? Does prow have a GCP service account I could grant the appropriate GKE IAM role on our clusters?

**Comment by clarketm** [comment]
@jlewi 

Currently, Prow supports only generic (i.e. provider-agnostic) cluster authorization mechanisms - either x509 certificates or [Kubernetes service account tokens](https://github.com/clarketm/kubernetes_test-infra/blob/4e8e146fee3b2eb1d111bfd3e8e0aaee9758b336/pkg/gencred/README.md#generate-a-service-account-token-for-a-cluster).

**Comment by scottilee** [comment]
@jlewi can you get Travis the permissions he needs?

**Comment by jlewi** [comment]
@scottilee I believe @clarketm has the permissions he needs.
https://github.com/kubeflow/internal-acls/blob/c28cd44c407faededac1df7ba015220d50c14411/ci-team.members.txt#L2

**Comment by jlewi** [comment]
See: GoogleCloudPlatform/oss-test-infra/pull/177

**Comment by scottilee** [comment]
@clarketm I know you just got back to work but friendly ping about this, let me know if you're missing or need anything!

**Comment by jlewi** [comment]
I think after GoogleCloudPlatform/oss-test-infra/pull/177 is merged we will want to ensure the prow job specs are in sync with our prow job specs for K8s. That PR has been open for a while and in the meantime some changes have been made to the prow jobs running on the K8s prow instance.

**Comment by scottilee** [comment]
@jlewi Since [#177](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/177) is merged can we close this?

**Comment by jlewi** [comment]
I think we just need to update the README #633
and then we can close this.
