### ISSUE TITLE
test-worker image should be released in the post-submit

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#501]
In the PR #500 updated the test-worker image, but the image is not refreshed, the image should be released in the post-submit.

/cc @jlewi

**Comment by jlewi** [comment]
The current gcr.io/kubeflow-ci/test-worker:latest image is pointing at
gcr.kubeflow-ci/test-worker@sha256:dd559f89b3cbd926ec563559995f25025eecc6290b3146f17f82d2f084d07ee2

Which is from Oct 2.

I just triggered a build to pick up the new image.

To auto-build it on post-submit we would just define an Argo workflow to be triggered from prow_config.yaml. That workflow could just run `make build-gcb`

@jinchihe I'm

**Comment by jinchihe** [comment]
@jlewi Great thanks!

**Comment by jlewi** [comment]
Here's a new image:
gcr.io/kubeflow-ci/test-worker:v20191029-fd24db8-e3b0c
