### ISSUE TITLE
periodic and postsubmit tests broken

### ISSUE THREAD

**Issue by lluunn** [kubeflow/testing#507]
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-postsubmit
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master
- mainly basic auth
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-periodic-master/1188840474232754176
- http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-periodic-master-kfctl-go-basic-auth-4176-e4a6?tab=workflow&nodeId=kubeflow-periodic-master-kfctl-go-basic-auth-4176-e4a6-1147472132&sidePanel=logs%3Akubeflow-periodic-master-kfctl-go-basic-auth-4176-e4a6-1147472132%3Amain

```
failed to build kfApp from URI /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-basic-auth-4176-e4a6/kfctl-aa7b/
tmp.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp: Could not configure basic auth; environment v
ariable KUBEFLOW_USERNAME not set
```

**Comment by lluunn** [comment]
From the log, the setup seems wrong

```
kfctl_go_test_utils.py     244 INFO     use_basic_auth=False
kfctl_go_test_utils.py     247 INFO     use_istio=True
kfctl_go_test_utils.py     105 INFO     Setting environment variables CLIENT_SECRET and CLIENT_ID
```

**Comment by jlewi** [comment]
Most recent periodic run
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1188082356003540992

Master was at
Your branch is up-to-date with 'origin/master'.
++ git describe --tags --always --dirty
/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-basic-auth-6616-f600/src/kubeflow/kubeflow is at ce4ad4b


This should include the fix.

**Comment by lluunn** [comment]
still seeing logs:
```
kfctl_go_test_utils.py     249 INFO     use_basic_auth=False
kfctl_go_test_utils.py     252 INFO     use_istio=True
```

And the line number is correct that it should have the fix https://github.com/kubeflow/kubeflow/pull/4420/files

investigating
