### ISSUE TITLE
katib test failed in periodic

### ISSUE THREAD

**Issue by lluunn** [kubeflow/testing#508]
<img width="1219" alt="Screen Shot 2019-10-30 at 10 50 54 AM" src="https://user-images.githubusercontent.com/32310205/67884595-53263f80-fb03-11e9-8c1d-08ad3e22bf70.png">

http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-periodic-master-kfctl-go-basic-auth-7210-3f73?tab=workflow&nodeId=kubeflow-periodic-master-kfctl-go-basic-auth-7210-3f73-4078077713&sidePanel=logs%3Akubeflow-periodic-master-kfctl-go-basic-auth-7210-3f73-4078077713%3Amain

```
NAME       READY   UP-TO-DATE   AVAILABLE   AGE
katib-db   1/1     1            1           8m16s

...
Exception: Deployment failed: katib-db
```

seems katib-db is up?

**Comment by lluunn** [comment]
I think kubectl just merged` desired=1 current=1` into `ready=1/1`
in the logs:
```
INFO|2019-10-30T16:09:43|/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-basic-auth-7210-3f73/src/kubeflow/kubeflow/testing/test_deploy.py|253| desired
_pods 1/1
INFO|2019-10-30T16:09:43|/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-basic-auth-7210-3f73/src/kubeflow/kubeflow/testing/test_deploy.py|254| current
_pods 1
INFO|2019-10-30T16:09:43|/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-basic-auth-7210-3f73/src/kubeflow/kubeflow/testing/test_deploy.py|255| uptodat
e_pods 1
INFO|2019-10-30T16:09:43|/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-basic-auth-7210-3f73/src/kubeflow/kubeflow/testing/test_deploy.py|256| availab
le_pods 8m10s
```

**Comment by lluunn** [comment]
we should get the number by `kgdepn kubeflow katib-db -o jsonpath='{.status.availableReplicas}'`

**Comment by jlewi** [comment]
Discussed with @lluunn 

I think we should just get rid of the current script and add a new test function to
https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kf_is_ready_test.py

Related: kubeflow/testing#509

**Comment by jlewi** [comment]
This is failing in presubmit as well and blocking it.

According to @lluunn this is because the format of kubectl changed and the test depends on this format.

We recently upgraded kubectl in our test worker images and that's what's causing the problem.
