### ISSUE TITLE
Upgrade kubectl to 1.14 in test-worker

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#510]
Tracking bug for upgrading kubectl to 1.14 in test-worker.

This is currently blocked on kubeflow/testing#508 the katib breaks with the newer version of kubectl so we need to fix the test first.

We had previously tried to upgrade the image to one with the latest version of kubectl and it broke.
See
https://github.com/kubeflow/testing/issues/501#issuecomment-547742939

Rolling back the latest image to
gcr.kubeflow-ci/test-worker@sha256:dd559f89b3cbd926ec563559995f25025eecc6290b3146f17f82d2f084d07ee2

Earlier today we had set it to
gcr.io/kubeflow-ci/test-worker:v20191029-fd24db8-e3b0c

Related PR: kubeflow/testing#500

**Comment by jlewi** [comment]
/cc @jinchihe 

@jinchihe If you need to upgrade the examples; you could modify the example tests to pin to a specific image rather than using latest.

**Comment by jinchihe** [comment]
@jlewi OK. Thanks. but why not pin to specific test-worker image tag? I think all test clusters will be >= 1.14, :-)

**Comment by jlewi** [comment]
If we pin the test worker image used by a particular test then when we want to update the test worker image we have to update all the tests.
