### ISSUE TITLE
Automatic merges with tide aren't working

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#52]
See #47 

* All status checks are green
* Status still says PR is not in the tide pool.
* Coveralls is not enabled for this repository so I don't think we are hitting 
  kubernetes/test-infra#7091

Background:
kubeflow/community#20

tide seems to be working for kubeflow/kubeflow.

**Comment by jlewi** [comment]
@BenTheElder @cjwagner Another day another repo :) Any idea what the problem is this time?

**Comment by BenTheElder** [comment]
@jlewi per the expanded merge requirements at https://prow.k8s.io/tide.html kubeflow repos need lgtm and approval. @qhuynh96 is working on a PR status page that we'll link to from the context (Eventually) to make this clearer. Looks like we just need to /lgtm

**Comment by BenTheElder** [comment]
And it just merged after I `/lgtm`ed it :-)

**Comment by jlewi** [comment]
@BenTheElder thanks.
