### ISSUE TITLE
cleanup_ci doesn't clean up instance groups properly

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/testing#528]
All the instance groups were skipped during GC because infra type couldn't be determined:
https://github.com/kubeflow/testing/blob/25b87a36f03c207f69abbc9e18500e9ac75647d0/py/kubeflow/testing/cleanup_ci.py#L324

the reason is because instance groups are not named as other resources:
- gke-apps-apps-cpu-pool-v1-a3e58689-grp
- gke-kf-vmaster-1124--kf-vmaster-1124--fae5daa0-grp
- gke-myapp2-myapp2-cpu-pool-v1-e8485b6e-grp
- k8s-ig--00bfab21c3a055cc

**Comment by jlewi** [comment]
@gabrielwen Which projects do the above instance groups belong to?

What clusters do the above instance groups belong to and how are we determining that its ok to GC them?

For example, what was the purpose of the GKE cluster named "gke-apps-apps-cpu-pool-v1-a3e58689-grp" ? How do we know its safe to GC it?

The IG named "gke-kf-vmaster-1124--kf-vmaster-1124--fae5daa0-grp" belongs to an auto-deployed cluster; so we should be applying the criterion for the auto-deployed clusters.
