### ISSUE TITLE
Garbage collect old Argo workflows / Argo UI unresponsive

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#53]
On our test cluster in project mlkube-testing. I'm noting Argo workflows going back as far as 22 days old.
I'm also knowing that the UI and kubectl are sluggish. 
I suspect this might be because there are so many workflows.

What is the garbage collection policy for workflows that have completed? Is there any?

**Comment by jlewi** [comment]
Navigating to a specific workflow doesn't seem to work either
http://testing-argo.kubeflow.org/timeline/kubeflow-test-infra/kubeflow-presubmit-tf-serving-image-387-12405f1-511-aec5;tab=workflow

**Comment by jlewi** [comment]
I tried manually deleting the older workflows as follows

Dump all workflows sorted by age to a file

```
kubectl get wf -a --sort-by='.metadata.creationTimestamp'  > /tmp/wf.list
```

Manually delete the lines corresponding to workflows I don't want to delete.

Then do

```
cat /tmp/wf.list | awk '{print $1}' | xargs kubectl delete wf 
```

**Comment by jlewi** [comment]
Deleting the workflows appears to have worked so it appears to be an issue with the UI not performing well when there are lots of workflows.

/cc @jessesuen @alexmt

**Comment by jessesuen** [comment]
Argo does not have a GC policy/configuration. It should though.

**Comment by jlewi** [comment]
UI is having problems again.

Currently 697 workflows

[wf.list.txt](https://github.com/kubeflow/testing/files/1850273/wf.list.txt)

Delete workflows more than a day old

**Comment by alexmt** [comment]
@jlewi, unfortunately, Argo GC is still not implemented. UI is not performing well since it does not have pagination (because kubernetes api does not have pagination yet)

As a workaround, you might try argo v2.1.0-alpha1 +.  UI had been migrated to React and can render much more workflows.

**Comment by jlewi** [comment]
@alexmt Great thank you so much.

**Comment by jlewi** [comment]
1330 workflows

Deleted workflows older than 3 days to make UI more responsive.

**Comment by lluunn** [comment]
deleted 1391 workflows older than 3d

**Comment by jlewi** [comment]
Deleted 307 workflows; older than 3d

**Comment by jlewi** [comment]
1726 workflows
Deleting 1601 workflows older >=3d

**Comment by jlewi** [comment]
Argo v2.2.0 now supports setting a TTLAfterSeconds flag.
https://github.com/argoproj/argo/blob/7864ad36788dc78d035d59ddb27ecd979f7216f4/pkg/apis/workflow/v1alpha1/types.go

We  need to do a couple things

1. Upgrade Argo
1. Start setting that on our workflows.
1. Consider adding an admission controller to ensure its set.

**Comment by jlewi** [comment]
Running get wf was having problems on my local machine but when I ran it from within cluster it succeeded. I think its probably because there's so much K8s master traffic.

**Comment by jlewi** [comment]
I deleted the namespace because deleting individual workflows wasn't working.

```
kubectl delete namespace kubeflow-test-infra
```

**Comment by jlewi** [comment]
Waiting for the namespace to be deleted. Hopefully that succeeds.

**Comment by jlewi** [comment]
Namespace was successfully deleted. 

Now redeploy test infra

```
kubectl create namespace kubeflow-test-infra
ks apply kubeflow-ci -c argo
```

ksonnet app is here:
https://github.com/kubeflow/testing/tree/master/test-infra

**Comment by jlewi** [comment]
Argo UI is backup

**Comment by jlewi** [comment]
I had to delete and recreate the nfs component

```
ks delete kubeflow-ci nfs-external
ks apply kubeflow-ci nfs-external
```

**Comment by jlewi** [comment]
Will be fixed by #300 which includes  a cron job to GC Argo workflows.

**Comment by jlewi** [comment]
See #324 seems like there's a problem with our cron job and we aren't GC'ing the resources.

**Comment by jlewi** [comment]
#267 Issue to monitor cron jobs.

**Comment by jlewi** [comment]
Haven't had problems in a while so closing this issue.
