### ISSUE TITLE
Tooling and processes to ensure licensing requirements for Docker images are satisfied

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#539]
We need tooling and processes to ensure that all the docker images we publish satisfy appropriate licensing requirements.

This is critical for 1.0

To begin with I think we can focus on docker images for applications going 1.0 with Kubeflow 1.0. I think we basically have two kinds of docker images

1. Docker images corresponding to python binaries
1. Docker images corresponding to go binaries

For each of these binaries we need to transitively pull all third party dependencies and ensure we satisfy licensing requirements.

**Comment by Bobgy** [comment]
Made PR for tools for automating go dependencies' licenses: https://github.com/kubeflow/testing/pull/540

**Comment by jlewi** [comment]
@zhenghuiwang could you provide an update on this?

**Comment by zhenghuiwang** [comment]
Update:

Filed several issues above.

For Golang image: follow [these instructions](https://github.com/kubeflow/metadata/blob/master/third_party_licenses/README.md) to add license files.

For NodeJS image: follow [these instructions](https://github.com/kubeflow/metadata/blob/master/frontend/gen_licenses.js) to add license files.

**Comment by jlewi** [comment]
@zhenghuiwang can we close this issue or is there more work to be done?
