### ISSUE TITLE
Add exclude directories support to prow_config.yaml

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#585]
Right now we support the ability to only trigger tests when certain files are matched.

It might also be good to have an exclude_dirs option.  In some cases it might be easier to
list which directories are excluded.

We should just have to modify the code here.
https://github.com/kubeflow/testing/blob/bb549cb65561e1d0bbd6bef4c812f0c3965f54be/py/kubeflow/testing/run_e2e_workflow.py#L253

**Comment by Swikar** [comment]
Jeremy can you assign this to me?
