### ISSUE TITLE
minikube testing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#6]
We should run E2E tests on minikube.
kube_test is supposed to help with this.

**Comment by jlewi** [comment]
Some thoughts on possible approaches.

- Investigate kube_test and see what it does
- Run minikube on a VM and run everything via ssh
   
This should map pretty well to our existing E2E tests. Our existing E2E tests are Argo workflows that just run series of scripts. So the only change we'd need to make is to execute those scripts via ssh on the remote VM rather than in the pod itself.

**Comment by mhausenblas** [comment]
@jlewi can you link to the Argo workflows pls? I might be interested in taking care of this …

**Comment by jlewi** [comment]
@mhausenblas Are you still thinking of taking this on?

**Comment by jlewi** [comment]
I did some initial experimentation this morning.

* I looked at [kubetest](https://github.com/kubernetes/test-infra/tree/master/kubetest) but it didn't seem to offer any support for minikube.

* I setup minikube on a GCE VM using driver=None.
* I was able to connect to that minikube deployment from a pod running in an actual GKE cluster by
  
  *  Copying the .kube directory to the pod from the VM
  *  Copying the .minikube directory to the pod from the VM
  *  Modifying .kube/config to change the paths of the .minikube files (certs)

* It looks like the K8s master is running on the GCE internal IP

* So E2E tests running on minikube should work nearly identical to our existing E2E tests on GKE. The only difference would be that we would need to deploy a K8s cluster via minikube.

**Comment by mhausenblas** [comment]
Thank you @jlewi and yes, I plan to work on it next week (on travel now) but if you want to have it earlier, feel free to start the work and I chime in when I'm back home?

**Comment by jlewi** [comment]
Sounds great. Let me see how far I can get this week.

**Comment by dlorenc** [comment]
Note that you can also use nested virtualization and the kvm2 driver on gce for a more traditional minikube testing setup.

**Comment by jlewi** [comment]
Basic testing is done.
We should consider whether we want to run some of our other tests on minikube as well.
