### ISSUE TITLE
URL for Argo workflows changed

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#60]
In gubernator we report the url for the worfklow UI as

```
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-tf-serving-image-387-f608b1a-532-1c41;tab=workflow
```
This doesn't appear to be valid anymore with the new version of the Argo UI.

I think we just want to use

```
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-tf-serving-image-387-f608b1a-532-1c41
```

@Jimexist would you mind sending another PR to fix this?

**Comment by Jimexist** [comment]
@jlewi i updated it in #62

**Comment by Jimexist** [comment]
if you can confirm that this issue is fixed by that PR it'll be great, thanks!

**Comment by jlewi** [comment]
This doesn't appear to be fixed.
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_testing/62/kubeflow-testing-presubmit/77/

Still reports as the workflow
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-tf-serving-image-445-bcec1a8-681-30cc?tab=workflow

We most likely need to rebuild the testing image since run_e2e_workflow.py is built into the test container.

**Comment by jlewi** [comment]
I take that back run_e2e_workflow.py should be checked out from kubeflow/testing via checkout.sh.

And the URLs now appear to work. Marking this as fixed.
