### ISSUE TITLE
applications tool should support printing out all application versions

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#600]
We should update the tool 
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/tools/applications.py

To print out the application version for all applications.

This would be useful for updating the versioning on the website.

We might even want to have it spit out a markdown table or shortcodes; something that we could easily copy and paste into the website.

**Comment by scottilee** [comment]
> We should update the tool
> https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/tools/applications.py

This file does not exist.
