### ISSUE TITLE
Tekton tasks and pipelines to run notebooks and generate reports

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#613]
Kubeflow relies heavily on notebooks for reporting and e2e testing.

We'd like to make it easier to run notebooks and generate reports for them.

One way to do that would be to create reusable [Tekton tasks](https://github.com/tektoncd/pipeline) to run notebooks (e.g. using papermill) and then upload an HTML version of the output to an object store like GCS or S3.

Then users could easily automate the running and generation of notebook reports just by adding tasks to a Tekton pipeline.

The task should be parameterized so that users just have to specify the parameters defining their notebook. Possible parameters

inputs:
  * Git repo containing the source notebook (using a Tekton Git resource)
  * Path within the repo to the notebook

Outputs:
  * Location where report should be published.

We should define a catalog of tasks inside kubeflow/testing and put the task there. Similar to 
https://github.com/tektoncd/catalog.

kubeflow/examples#735 provides an example of using papermill to execute a notebook, then running nbconvert to convert to html, and then uploading it to GCS. That could be as a model of what a Tekton task might do.

As a follow on issue we might want to investigate using [commuter](https://github.com/nteract/commuter) to view these notebooks

**Comment by jlewi** [comment]
I think @gabrielwen is working on this.

@gabrielwen any update on this?

**Comment by StephennFernandes** [comment]
I would like to work on this issue as a part of GSOC 2020

**Comment by rujual** [comment]
Hi! Is there any issue created for adding support for larger output data types such as DataFrames similar to the kfp function func_to_container_op  directly in Tekton, without converting to str or OrderedDict from one Pipeline block to the next (like it does in kfp) ?

**Comment by 11fenil11** [comment]
@sarahmaddox I would like to contribute on this issue during GSoC journey.

**Comment by jlewi** [comment]
#622 included some initial tekton tasks and pipelines for running our E2E tests.
I'm currently trying to get those running against our auto deployed blueprints per:
kubeflow/gcp-blueprints#42
