### ISSUE TITLE
label sync needs to auto-sync the config to the cluster

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#624]
Our label sync process currently relies on manually updating the config map when things change.
https://github.com/kubeflow/testing/tree/master/label_sync

Lets try to use gitops and anthos CM for this.
https://cloud.google.com/anthos-config-management/docs/quickstart

**Comment by Swikar** [comment]
Jeremy, I noticed Anthos setup is done. I am not sure fully completed or not? Can you tell me what portion of work still require for this PR?

**Comment by Swikar** [comment]
@jlewi Regarding https://github.com/kubeflow/testing/issues/624 How far has been completed and how much work still reamains? I am currently working on that PR. I am reviewing this https://cloud.google.com/anthos-config-management/docs/quickstart (

**Comment by jlewi** [comment]
@Swikar I think this was fixed by #625

**Comment by Swikar** [comment]
Oh okay it seemed to me👍
