### ISSUE TITLE
Move prow jobs onto the Kubeflow testing cluster

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#627]
This is issue is tracking moving Kubeflow's prow jobs onto its own build clusters.
https://github.com/kubernetes/test-infra/blob/master/prow/scaling.md#separate-build-clusters

This should allow better isolation and debuggability because we will have access to the prow pod logs.

/assign @clarketm

**Comment by jlewi** [comment]
PR #2 
kubernetes/test-infra#16961

Before closing this issue we should update the README.
https://github.com/kubeflow/testing#no-results-show-up-in-gubernator

Since the pod logs should now be accessible in the kubeflow-ci cluster

**Comment by clarketm** [comment]
I will update the README accordingly.

/assign @clarketm

**Comment by jlewi** [comment]
Thanks. @clarketm 
Duplicate of #475

**Comment by jlewi** [comment]
Duplicate of #475
