### ISSUE TITLE
Use Tekton (instead of K8s jobs) to cleanup the Kubeflow CI project

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#654]
We currently use a K8s job and cron job to regularly run `cleanup_ci.py` to cleanup the Kubeflow
test infrastructure.

The K8s Job for oneoff runs is:
https://github.com/kubeflow/testing/blob/master/test-infra/cleanup-kubeflow-ci-deployment.yaml

The cron job is still defined here using ksonnet
https://github.com/kubeflow/testing/blob/master/test-infra/ks_app/components/cleanup-ci-cron.jsonnet

I think we should switch to using Tekton tasks/pipelines rather than a regular K8s job.  Tekton has a couple advantages

* We can use Tekton to provide logic for checking out git repos rather than relying on our won scripts
* We can easily have multiple steps or tasks
   * This is useful for doing things like creating a Kubernetes context to use for cleanup
* We are already using Tekton for autodeploy and the dashboard is serving at:
  https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/tekton
* We can reuse tasks/pipelines between oneoff runs and cron runs.

To run it as cronjob we can create a regular k8s cronjob that mounts pipelinerun via a configmap
and then run `kubectl create -f`.

**Comment by Jeffwan** [comment]
Do we have plan to migrate argo based jobs to Tekton?

**Comment by jlewi** [comment]
@Jeffwan I think long term that's where we want to go.
