### ISSUE TITLE
Setup buildcop

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#658]
We need to setup an appropriate buildcop team and "rotation" in order to spread the load of managing the CI/CD infrastructure along.

Here are  the big ticket items

1. Identify appropriate folks to be on the build copy rotation
    * These should be folks with a long track record of contribution and involvement in Kubeflow
    * There is non trivial setup to be done getting folks setup with access to kubeflow-ci

1. Document process for getting people added to the buildcop team.

**Comment by jlewi** [comment]
Process looks like the following today

1. Send a PR like #242 to add individuals to ci-team@kubeflow.org
1. Merge PR
1. Ask/wait for jlewi@ to manually sync the groups
    * Really need to automate this per kubeflow/internal-acls#22

We should document this in
https://github.com/kubeflow/testing/tree/master/playbook

**Comment by Swikar** [comment]
@jlewi I am interested in buildup team. Can you add me when you start building team? I expect team member will get workshop (mini training), is it true? Thanks

**Comment by scottilee** [comment]
> 1. Send a PR like #242 to add individuals to [ci-team@kubeflow.org](mailto:ci-team@kubeflow.org)

The PR link looks incorrect, can you fix?

**Comment by jlewi** [comment]
It looks like Tekton has successfully setup a buildcop.

[Tekton Proposal](https://docs.google.com/document/d/1QJV0z2bMXdz_BZOkBwfxIP1BiktUb8c1lcifwqxF5wg/edit#heading=h.6fsxjbh35nu5)

[Tool to automate buildcop rotation](https://github.com/tektoncd/plumbing/tree/master/bots/buildbot)

Looks like granting of appropriate permissions is still manual.
