### ISSUE TITLE
NFS is full - tests are failing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#659]
NFS is full.

@Jeffwan said he would take care of this once we grant him permission;
PR to add him to the ci-team is pending in kubeflow/internal-acls#242

**Comment by jlewi** [comment]
@Jeffwan I updated the groups so you should have permission.

**Comment by Jeffwan** [comment]
I will check playbooks today and get some hands on experiences on it. Hopefully fix all the problems today.

**Comment by jlewi** [comment]
@Jeffwan is reporting permission errors.

Here's confirmation he is a member of ci-team@kubeflow.org

```
gam print group-members group ci-team@kubeflow.org
Getting members for ci-team@kubeflow.org (1/1)
group,id,email,role,type,status
ci-team@kubeflow.org,102598489312679702611,cartick@google.com,MEMBER,USER,
ci-team@kubeflow.org,104469422128724790835,clarketm@google.com,MEMBER,USER,
ci-team@kubeflow.org,01y810tw3wgd34q,google-team@kubeflow.org,MEMBER,GROUP,ACTIVE
ci-team@kubeflow.org,112550063030247762746,hejinchi@cn.ibm.com,MEMBER,USER,
ci-team@kubeflow.org,117579383194938037219,kam.d.kasravi@intel.com,MEMBER,USER,
ci-team@kubeflow.org,109338916304722063581,kunming@google.com,MEMBER,USER,
ci-team@kubeflow.org,109636147728115581185,lunkai@google.com,MEMBER,USER,
ci-team@kubeflow.org,111760271373344466402,seedjeffwan@gmail.com,MEMBER,USER,
ci-team@kubeflow.org,100946222206075643186,yangpa@google.com,MEMBER,USER,
jlewi@jlewi-glaptop2:~/git_kubeflow-internal-acls$ 
```

Here's the IAM policy.

[kubeflow-ci.iam.policy.txt](https://github.com/kubeflow/testing/files/4617548/kubeflow-ci.iam.policy.txt)

ci-team@kubeflow.org should be a problem.

I think its possible the owner permission might not be addable through groups since owners may need to be invited.

**Comment by Jeffwan** [comment]
em. IAM side looks fine, ci-team is associate with owner role. 

```
- members:
  - group:ci-team@kubeflow.org
  - group:google-team@kubeflow.org
  - serviceAccount:kubeflow-deploy-admin@kubeflow-ci.iam.gserviceaccount.com
  - serviceAccount:kubeflow-releasing@kubeflow-releasing.iam.gserviceaccount.com
  - user:jlewi@kubeflow.org
  role: roles/owner
```

**Comment by jlewi** [comment]
Looks like the problem wasn't owner role but that @Jeffwan was typing the wrong command he had `--project` in the wrong position.

**Comment by Jeffwan** [comment]
> Looks like the problem wasn't owner role but that @Jeffwan was typing the wrong command he had `--project` in the wrong position.

Thanks help figure out the problem.

clean up is in progress and it's a little bit slow. 

before clean up. 
```
root@debug-worker-0:/mnt/test-data-volume# df
Filesystem             1K-blocks       Used Available Use% Mounted on
xxxxx:/kubeflow 5225463808 4412182528 549863424  89% /mnt/test-data-volume
```

I spot check a few folders, every test case takes 300M-400M, it would be great to have cron job to clean up historical build jobs periodically 

```
root@debug-worker-0:/mnt/test-data-volume# du -sh ./kubeflow-manifests-presubmit-unit-883-14194f6-3088-f633
418M	./kubeflow-manifests-presubmit-unit-883-14194f6-3088-f633

root@debug-worker-0:/mnt/test-data-volume# du -sh ./kubeflow-periodic-0-5-branch-kfctl-go-iap-2131-5d83
318M	./kubeflow-periodic-0-5-branch-kfctl-go-iap-2131-5d83
```

**Comment by Jeffwan** [comment]
hm..

The problem is probably on iNode, here's the status we just release some inode resources. it's probably 100% without any IFree before cleaning up.

```
root@debug-worker-0:/mnt/test-data-volume/kubeflow-periodic-examples-unittests-0483-596b# df -i
Filesystem               Inodes     IUsed   IFree IUse% Mounted on
xxxx:/kubeflow 164626432 163879212  747220  100% /mnt/test-data-volume
```

**Comment by jlewi** [comment]
@Jeffwan  what does the problem is iNodes mean? I've never been able to get deleting files to work. I've always had to delete and recreate the NFS volume.

The tests are supposed to clean up their folder at the end but in a variety of cases that doesn't happen.

With the new Tekton pipelines we no longer rely on NFS to pass data among the different precisely because using NFS led to so many problems.

**Comment by jlewi** [comment]
Here's a stackdriver plot of free disk space
![free_space](https://user-images.githubusercontent.com/777219/81822105-8b153300-94e7-11ea-8769-b9d9914d36d6.png)

Looks like we are at 20% available. Looks like we never dropped below 10% available.

**Comment by Jeffwan** [comment]
After clean up yesterday, it's good enough for now. If it doesn't have a cronjob doing clean up, we need one. 

```
root@debug-worker-0:/# df
Filesystem             1K-blocks       Used  Available Use% Mounted on
10.86.7.242:/kubeflow 5225463808 3692606464 1269438464  75% /mnt/test-data-volume

df -i
Filesystem               Inodes     IUsed    IFree IUse% Mounted on
10.86.7.242:/kubeflow 164626432 139561314 25065118   85% /mnt/test-data-volume
```

**Comment by Jeffwan** [comment]
> @Jeffwan what does the problem is iNodes mean?

Based on the check yesterday, there's no Inodes available which means test can not create files in NFS even with some spaces (10% space is still available). Since it fetch codes and manifests, it create lots of small files which can easily eat out all Inodes resources.

**Comment by jlewi** [comment]
Thanks @Jeffwan

**Comment by jlewi** [comment]
@Jeffwan going to close this looks like tests have been fixed. Thanks!
