### ISSUE TITLE
GitOps for kubeflow-releasing infrastructure

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#693]
We need to setup kubeflow-releasing to be administered via GitOps.

In particular we'd like to make it easy to grant people the permissions they need and record this.

Right now we use Google groups which isn't great because we have to manually sync them.

A better approach would be to use CNRM and ACM.

We recently setup 
https://github.com/kubeflow/community-infra/issues

This is running in project kf-kcc-admin  it should have access to the folder to community.

We could move kubeflow-releasing into the ci-cd folder and then grant appropriate permissions to administer that folder from the kf-kcc cluster.

**Comment by andreyvelich** [comment]
@jlewi So we want to automatically give permission to the `kubeflow-releasing` GCP project after updating members in  https://github.com/kubeflow/internal-acls/blob/master/release-team.members.txt, right ? 
As I know, currently we need to manually sync the groups to add new account.

Please, can you show me an example how it works for `kf-kcc-admin` project in https://github.com/kubeflow/community-infra?

**Comment by jlewi** [comment]
@andreyvelich There are two different approaches and we probably want to do both.

kubeflow/internal-acls#22 is tracking automatically sync'ing Google groups. We will eventually want to implement that at some point as there are lots of uses for Google groups and we'd like to be able to administer membership via GitOps.

GCP infrastructure can be administered via GitOps. This works as follows

1. We use [Cloud Config Connector](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall) to manage GCP infrastructure as K8s resources
1. Cloud Config Connector contains resources to administer IAM permissions e.g. [IAM Policy Member](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampolicymember)
1. We use GitOps tooling, [ACM](https://cloud.google.com/anthos/config-management) to sync K8s resources from a Git Repo to the K8s cluster

For more infra on how we are using this see
https://github.com/kubeflow/community-infra

For this particular issue; we need to figure out how we want to incorporate project `kubeflow-releasing` into our GitOps setup. This means figuring out the folder/project organization and IAM setup so we grant appropriate permissions to CNRM and ACM without over provisioning access to kubeflow-releasing.

**Comment by andreyvelich** [comment]
@jlewi Can we setup GitOps for existing `kubeflow-releasing` GCP project?
Or Config Connector will not allow update existing `kubeflow-releasing` project with appropriate IAM?

**Comment by jlewi** [comment]
@andreyvelich its technically possible; would need to think through the permission model and see if it makes sense.

**Comment by andreyvelich** [comment]
Maybe we can start with giving owner/editor permission for this group: https://github.com/kubeflow/internal-acls/blob/master/release-team.members.txt ?
So they can get access to the `kubeflow-releasing` project.

If anyone wants to join release-team, just submit the PR with additional `IAMPolicyMember` with appropriate role.

**Comment by jlewi** [comment]
@andreyvelich The release team is already an editor of kubeflow-releasing project. See attached
[iam-policy.txt](https://github.com/kubeflow/testing/files/5218705/iam-policy.txt)

**Comment by andreyvelich** [comment]
@jlewi Yes, but as mentioned before do we want to setup [GitOps project](https://github.com/kubeflow/community-infra/tree/master/prod/namespaces) for them, at least ?

Later, we can add more IAM permissions without editing [release-team.members.txt](https://github.com/kubeflow/internal-acls/blob/master/release-team.members.txt).

**Comment by jlewi** [comment]
@andreyvelich Lets back up, we need to figure out who is going to own and maintain this infrastructure; i.e. kubeflow/testing#737

The OWNERs can then figure out

* Where we are
* Where we need to go
* How we get from here to there
