### ISSUE TITLE
Create more generic testing files based on tf-operator python files

### ISSUE THREAD

**Issue by jose5918** [kubeflow/testing#71]
I'm referring to this set of files: https://github.com/kubeflow/tf-operator/tree/master/py

For example there should be a generic version `deploy.py`  to deploy a cluster without tf specific params such as https://github.com/kubeflow/tf-operator/blob/master/py/deploy.py#L144

**Comment by jlewi** [comment]
/lifecycle obsolete

We no longer rely on deploy but instead use kfctl.
