### ISSUE TITLE
Truncate workflow name in prow_config.yaml

### ISSUE THREAD

**Issue by jose5918** [kubeflow/testing#72]
Found  that if the workflow name is too long in prow_config.yaml I get this error:
```
Pod "kubeflow-pytorch-operator-presubmit-pytorchjob-e2e-13-1a13f4d-3-17ac-2950311768" is invalid: metadata.labels: Invalid value: "kubeflow-pytorch-operator-presubmit-pytorchjob-e2e-13-1a13f4d-3-17ac": must be no more than 63 characters
```
Should probably truncate or provide a warning to to the user.

**Comment by jlewi** [comment]
I believe all our workflows are properly truncating the names right now so I'm going to close this.
