### ISSUE TITLE
Auto Deployments are failing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#725]
Latest deployment
https://kf-vbp-0709-37c.endpoints.kubeflow-ci-deployment.cloud.goog/

It looks like the deployment script was never able to connect to the GKE master

Logs query

```
resource.type="k8s_container"
resource.labels.cluster_name="kf-ci-v1"
labels."k8s-pod/tekton_dev/taskRun" = "deploy-kf-master-s8v7k-deploy-gcp-sgm26"
```

```
kubectl --context=kf-vbp-0709-37c apply --recursive=true -f ./.build/istio/Base/Base.yaml
 unable to recognize "./.build/istio/Base/Base.yaml": Get https://35.192.0.225/api?timeout=32s: dial tcp 35.192.0.225:443: i/o timeout
```

**Comment by jlewi** [comment]
Lets delete the existing cluster to force a redeploy.

```
kubectl delete gcp -l kf-name=kf-vbp-0709-37c
```

**Comment by jlewi** [comment]
Looks like a transient issue

**Comment by mnmami** [comment]
Same happened to me, the cluster was all of the sudden irresponsible (GCP). So had to delete and restart.
