### ISSUE TITLE
Suggest supporting tekton_setup in prow_config.yaml

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#735]
Suggest  supporting tekton_setup in prow_config.yaml as below:
<pre>
      <b>tekton_setup: kubeflow/testing/tekton/testing/dummy-setup-run.yaml
      tekton_setup_params:
        - name: utter
          value: bar</b>
      tekton_run: kubeflow/testing/tekton/testing/nb-test-run.yaml
      tekton_params:
        - name: testing-cluster-pattern
          value: 'kf-v1-(?!n\d\d)'   
      name: tekton-v1
      include_dirs:
        - py/*     
      tekton_teardown: kubeflow/testing/tekton/testing/dummy-teardown-run.yaml
      tekton_teardown_params:
        - name: utter
          value: bar
</pre>

We would like to enhance KFServing CI testing with Tekton, there are 20+ steps in the CI tests. If we define all steps as `taskSpec` , the `pipelineRun` is very long, and hard to maintain and read. so I would like define some Tekton `Task` and `pipeline`, and add that as `taskRef`. If so we need to apply the tasks before applying the `pipelineRun`. so I think **that's better to have a `tekton_setup` (can use `taskSpec` for one task) to setup cluster, and then apply those `pipeline` and `tasks` by `Kustomize`** before submit `pipelineRun`, and then run the CI testing. Finished testing, we can use tekton_teardown to upload result and delete cluster.

@jlewi comments? Any better solution? Great thanks!

**Comment by jlewi** [comment]
@jinchihe Did you consider just defining tasks and pipelines which are sync'd via git to the cluster? Then your pipelinerun can just contain a reference to your pipeline. This is what we are currently doing. 

See: https://github.com/kubeflow/testing/blob/master/docs/tekton.md#kubeflows-catalog-of-reusable-tasks-and-pipelines

**Comment by jinchihe** [comment]
@jlewi we can reused some tasks/pipelines that's already synced in the cluster for some common case. But for other cases, no tasks/pipelines can be referred,  and better to do some preparatory works by `tekton_setup` (my suggestion). For example, KFServing need to setup a cluster to install specified Isito/Knative to test. And another cases, for other repos, Maintainer may enhance CI test by using tekton, they can use `tekton_setup` step  to apply they defined tasks/pipelines before refer that in pipelineRun. Thanks.

**Comment by jinchihe** [comment]
By the way, if we created a cluster in the `tekton_setup ` (how to check if created new cluster?), the `tekton_run` should use new cluster.

**Comment by jlewi** [comment]
@jinchihe So IIUC you are proposing to add a test setup fixture? So the flow would be

1. Run the tekton_setup workflows (e.g. to create a cluster)
1. Run 1 or more Tekton workflows that run against the cluster created in the previous step
1. Run the teardown?

**Comment by jinchihe** [comment]
@jlewi Yeah, and the the tekton_setup workflows also may create/apply the `tasks` which is used in step2.

**Comment by jlewi** [comment]
Did you consider just having a single Tekton pipeline that would run the setup fixture and then the subsequent steps? 

I think right now Tekton doesn't have great support for nested pipelines but I think that's coming with custom tasks and probably something we  need for KFP on Tekton.

The teardown is a workaround for the fact that Tekton didn't have a finally statement. Now that finally is supported we should start using that.

**Comment by jinchihe** [comment]
> Did you consider just having a single Tekton pipeline that would run the setup fixture and then the subsequent steps?

@jlewi Yeah, we can do all tasks in a single Tekton pipeline for cluster setup, but I want to apply the `pipelineRef` and `taskRef`, I do not want to inject all referred pipeline and tasks into one pipelineRun, that's huge and hard to maintain.  If the referred pipeline and tasks, we need to execute `make hydrate` as docs here? https://github.com/kubeflow/testing/blob/master/docs/tekton.md#kubeflows-catalog-of-reusable-tasks-and-pipelines I think that's not convenient. so personally better to support a setup steps.


> The teardown is a workaround for the fact that Tekton didn't have a finally statement. Now that finally is supported we should start using that.

Yes, tekton support finally now, great feature.

**Comment by jlewi** [comment]
@jinchihe Why couldn't you continue to use pipelineRef and taskRef? 

Your Tekton pipeline could launch other Tekton pipelines however you want. e.g. The first task in you Tekton pipeline could be paramterized with a pipelineRef for the setup task and then just launch that Tekton pipeline and wait for it to finish.

In other words, instead of having run_e2e_workflow.py construct a "DAG" of pipelines to run we could just use Tekton to construct a "DAG" of pipelines to run.
