### ISSUE TITLE
Grant appropriate IAP permissions to access tekton test UI

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#736]
I'm not sure here is right way (or testing repo?) to log this since we need to grant appropriate IAP permissions, but commented as @jlewi 

I want to check tekton test ui, but cannot access, how to apply that? Thanks.
```
You don't have access
Troubleshooting Info
User:hejinchi@cn.ibm.com
URL:https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/tekton/
If you should have access, please contact abhishek@google.com and provide the troubleshooting info above.
```

From @jlewi comments:
```
We will need to grant appropriate IAP permissions. Please file an issue. We can probably make it public.
```

**Comment by jinchihe** [comment]
@jlewi Sounds great. Thanks!

**Comment by jlewi** [comment]
To clarify this is not something I plan on tackling so someone else will need to pick this up in order to make it happen.

**Comment by jinchihe** [comment]
@jlewi @scottilee I think we need to address this otherwise Tekton cannot be used for Kubeflow CI tests since PR owners cannot see the pipelines. As my understanding, someone from Google can help to do this, right? any plan? Thanks.

/cc @yuzisun

**Comment by jlewi** [comment]
@scottilee Isn't a Googler and I'm not sure how many cycles he has to dedicate to test infrastructure.

The meta issue here is discussed in kubeflow/testing#737  We don't currently have folks dedicated to maintaining CI/CD infrastructure for all of Kubeflow and we need to figure out how to address that.

**Comment by jlewi** [comment]
@jinchihe As a quick fix I granted groups ci-team@ and ci-viewers@ IAP http accessor role so folks in those google groups should be able to address it.

It looks like @jinchihe you were already a member of ci-team@ and that ci-team@ actually has the permission needed to effect this change.

**Comment by jinchihe** [comment]
@jlewi Great! Thanks a lot!
