### ISSUE TITLE
Add some supports to make testing infra run on AWS

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/testing#748]
AWS plans to add some periodical tests for workshop https://github.com/aws-samples/eks-kubeflow-workshop. I think it makes more sense to setup this testing infra on AWS. I would like to leverage existing `kubeflow/testing` to test the repo and current blocking issue is some of the logics are GCP only. 

What we plan to do is still reusing the repo, add AWS utils, like `upload_to_s3`, `setup_iam_for_serviceaccount` etc, probably extract some common logic if needed and eventually make AWS an alternative platform to run testing infra. 

We'd like to put some time to help maintain common code base, help testing Tekton solution as well.  I am trying to get some feedbacks if this is a reasonable request and make sense to folks maintaining kubeflow/testing.

@Bobgy @jlewi @rmgogogo @pingsutw

**Comment by jlewi** [comment]
I think the setting up additional test infra on AWS is a great idea.
Putting AWS related testing tools in kubeflow/testing makes sense to me.

**Comment by PatrickXYS** [comment]
Created another issue to track aws-kf-ci-bot account's permission settings and webhook management 

https://github.com/kubeflow/internal-acls/issues/348

**Comment by PatrickXYS** [comment]
/reopen 

Not yet solved all the blocking issue

**Comment by PatrickXYS** [comment]
Close in favor of Optional-Test-infra working properly.

/close
