### ISSUE TITLE
Add labels to workflows

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#75]
Related to #72  (truncate workflow name)

Right now we encode a lot of information in the workflow name. The pattern is 

{ORG}-{REPOSITORY}-{PROW-JOB-TYPE}-{WORKFLOW-NAME}-{PR-NUMBER}-{RANDOMNESS}

It would be good to start using labels to represent this information. This would make it easier to filter and select workflows.

**Comment by RustamGimadiev** [comment]
oh, any updates? this feature can allow building really cool CI processes around Kubeflow, can I help here?
