### ISSUE TITLE
Create fsnotify watcher: too many open files

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/testing#751]
```
/mnt/test-data-volume/kubeflow-kfserving-presubmit-e2e-1047-1a2fe6f-5248-8696/src/kubeflow/testing is at d4394ea
failed to create fsnotify watcher: too many open files
```

Reported by @yuzisun

**Comment by Jeffwan** [comment]
File descriptors on the target node have been exhausted. The better way to handle this is to ssh to node and kill the process take many descriptors. The other easier way is to remove node from cluster and I think GCP node group will add one more into cluster. 

This should not be reproduced all the time. Once the new test is scheduled on the other node, it should pass.

**Comment by Jeffwan** [comment]
container should inherit host settings. I think ci-team may not have node permissions, check sysctl value, we get following values

```
root@debug-worker-0:/mnt/test-data-volume# sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches = 12288
```

**Comment by yuzisun** [comment]
@Jeffwan It is possible that some of my previous change in PR https://github.com/kubeflow/kfserving/pull/1047 caused the test volume issue, not sure, but now I try other existing KFServing PRs it got the same issue.

**Comment by Jeffwan** [comment]
Deleting above long running `kfserving-presubmit` test helps. Seem that's the processes having the issue. Thanks for the clues. @yuzisun. I will resolve this issue

**Comment by yuzisun** [comment]
Thanks @Jeffwan for the help!
