### ISSUE TITLE
Prevent tests from creating clusters and other resources in project kubeflow-ci after 09/01

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#752]
Follow on to #749.  Some tests are still dynamically provisioning GCP resources (e.g. clusters) inside project kubeflow-ci. This can cause problems because an ill-behaved test can end up eating all the quota.

In #749 we disabled the ability of tests to create GKE clusters (via IAM permissions) in order to flush out which projects were still relying on this functionality.  It looks like the following work groups need to update their tests

@kubeflow/wg-automl-leads 
@kubeflow/wg-training-leads 
@kubeflow/wg-serving-leads 

Per #749 a temporary extension was given to these work groups to continue using kubeflow-ci while they figure out alternative solutions.

I'm setting 09/01 as a deadline. After 09/01 the IAM permissions will be updated to remove the ability to create GKE clusters within kubeflow-ci. Any tests which still depend on kubeflow-ci at that point will fail until alternative solutions are found.

**Comment by PatrickXYS** [comment]
I think this issue is resolved by WG already

/close
