### ISSUE TITLE
gcloud build failed due to network issue

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/testing#753]
Recently KFServing CI build image aways failed due to network issue. Guess that's caused by cluster or `gcloud build` network problem?

```
Activating service-account
Activated service account credentials for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
Copy source to GOPATH
Creating temporary tarball archive of 168 file(s) totalling 1.4 MiB before compression.
Uploading tarball of [.] to [gs://kubeflow-ci_cloudbuild/source/1598927047.71441-106d5e9c40ff43119fbc7f1c8507080a.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/kubeflow-ci/builds/b375ed94-487c-4515-bf70-33cf579cc38d].
Logs are available at [https://console.cloud.google.com/cloud-build/builds/b375ed94-487c-4515-bf70-33cf579cc38d?project=593963025935].
ERROR: (gcloud.builds.submit) [Errno 104] Connection reset by peer
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach
```

**Comment by jinchihe** [comment]
@jlewi do you know if there any changes about network of cluster or `gcloud build`? Thanks.

**Comment by jlewi** [comment]
Could be an IAM issue 
https://github.com/kubeflow/testing/issues/749#issuecomment-678314439

I think you gcloud build might require roles/logging.viewer if its tailing the logs which we might have removed per above issue and might need to be added back.

**Comment by jinchihe** [comment]
@jlewi Thanks. I think that's not related with IAM issue, since KFServing has 11 image build components in CI, most of building can be succeed, but there are random few building component will be failed due to network issue.
