### ISSUE TITLE
Tekton CD Project Questions

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/testing#762]
Per Tekton CD Project, it's developed under GCP Project `kf-releasing`, build&publish image to GCR registry `kubeflow-images-public`. 

So my question is, is this possible that Google will expire the IAM permission to the GCR registry for Tekton CD in the future as we did for [katib](https://github.com/kubeflow/katib/issues/1332) 

If so, there will be a release issue for training WG + manifests + kubeflow/kubeflow.

/cc @jlewi

**Comment by jlewi** [comment]
Yes. Each wg needs to take ownership of its release process and artifacts. This means each WG should spin up its own release infrastructure as well as any infrastructure to publish release artifact (e.g. docker registry).

**Comment by jlewi** [comment]
kubeflow/community#433 - For notebooks

I also created a Kanban board to start tracking this.
https://github.com/orgs/kubeflow/projects/42?add_cards_query=is%3Aopen
