### ISSUE TITLE
Convert Python unittest Argo Workflow to Tekton

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#769]
Per #768 we need to get rid of the dependency on NFS by converting our Argo workflow for running python unittests to using Tekton.

The Argo Workflow is defined here.
https://github.com/kubeflow/testing/blob/4e02994179cfbdc3f3dd93ffb7c6ded6c9aad11c/py/kubeflow/testing/ci/kf_unittests.py#L192

We can model our Tekton pipeline off of our go unittests pipeline
https://github.com/kubeflow/testing/blob/master/tekton/runs/go-test-run.yaml
https://github.com/kubeflow/testing/blob/master/tekton/templates/pipelines/go-test-pipeline.yaml
https://github.com/kubeflow/testing/blob/master/tekton/templates/tasks/go-tests.yaml

The overall structure is largely the same

* We need to create two Tekton tasks
  
  * The first will run lint; i.e. this [argo step](https://github.com/kubeflow/testing/blob/4e02994179cfbdc3f3dd93ffb7c6ded6c9aad11c/py/kubeflow/testing/ci/kf_unittests.py#L217)
  * The second will run the unittests; i.e. this [argo step](https://github.com/kubeflow/testing/blob/4e02994179cfbdc3f3dd93ffb7c6ded6c9aad11c/py/kubeflow/testing/ci/kf_unittests.py#L197)

These tasks will be very similar to 
https://github.com/kubeflow/testing/blob/master/tekton/templates/tasks/go-tests.yaml

i.e. there will be two steps in each
* Run the tests or lint
* Run copy-artifacts

/cc @subodh101 @Jeffwan @PatrickXYS

**Comment by subodh101** [comment]
@PatrickXYS I think I would be able to do it.
Also, I have started working on it in case of double work. Sorry for not assigning earlier.

**Comment by PatrickXYS** [comment]
@subodh101 Sounds good, thanks for helping!

**Comment by Jeffwan** [comment]
@subodh101 @PatrickXYS 

When you help on the migration, please try not to delete Argo related codes unless you are 100% sure it's not being used. 
https://github.com/kubeflow/testing/issues/774

We can have some clean up later once 1.2 get released. We have a few PRs blocked this morning

**Comment by jlewi** [comment]
> When you help on the migration, please try not to delete Argo related codes unless you are 100% sure it's not being used.
#774

The deleted code was ksonnet code. I was the one who said to delete it.

Deleting the ksonnet workflows is fair game IMO. This is the risk WGs assume per #737 by relying on infra that is being maintained 20%.

**Comment by subodh101** [comment]
@Jeffwan Apologies, work got delayed.

The main issue of NFS out of space is resolved.

https://github.com/kubeflow/testing/pull/775#issuecomment-722007007 this can be resolved later.
What essential we can do is:
- Get rid of copy-artifacts task as it is parsing xml and uploading results to gcs. However, those logs are visible in pods (i.e. gcp logging in my case).
- Also, for faster development, the logs of atleast the failed jobs can be made visible over the prow.

cc: @jlewi 

Again as mentioned, let's do this after 1.2 gets released.

I thought about adding back the test code of ksonnet i.e.https://github.com/kubeflow/testing/pull/771/files#diff-7e990d2529a3ae46c728ac39cc127edb6f1668f16a0659feb81bdc9023b1b7e7L26-L128 for time being. But this involves reverting many changes from https://github.com/kubeflow/testing/pull/463 and it doesn't make sense as we are getting rid of it.
Looks like nobody is maintaining [ksonnet](https://github.com/ksonnet/ksonnet) any more.

**Comment by jlewi** [comment]
@subodh101 Looks like I missed a minor thing in my review that I think we should fix before closing this issue.

The PipelienRun shouldn't embed the pipeline-spec [here](https://github.com/kubeflow/testing/blob/b2b4b2f06ce48b3f18cf21bbc47b42efa9913a12/tekton/runs/py-unittests-run.yaml#L23)
    
    * Instead we should define a pipeline in https://github.com/kubeflow/testing/tree/master/tekton/templates/pipelines 
    * All PipelineRuns should then reference that pipeline
    * This way if we change the python test pipeline all tests get updated

**Comment by jlewi** [comment]
@subodh101 I noticed another issue. The copy-artifacts step needs to set the python path to

```
    - name: PYTHONPATH # N.B. This uses the version cached in the docker image.
      value: /srcCache/kubeflow/testing/py
```
as here
https://github.com/kubeflow/testing/blob/b2b4b2f06ce48b3f18cf21bbc47b42efa9913a12/tekton/templates/tasks/go-tests.yaml#L71

We want to use the version of copy-artifacts baked into the docker image since not all tests will be using kubeflow/testing and checking out that repo.

**Comment by subodh101** [comment]
Understood. Thanks!
Will make the changes!👍

**Comment by Jeffwan** [comment]
> Deleting the ksonnet workflows is fair game IMO. This is the risk WGs assume per #737 by relying on infra that is being maintained 20%.

Agree. Let's remove all of them a little bit late. Current workflow fetches kubeflow/testing master changes which is not a stable solution. This needs some improvement as well. We already use testing image, no need to download the code separately.

**Comment by subodh101** [comment]
Current python unittests pipeline is specific to kubeflow/testing repository only.
I will make it more like `environment as code` such that all the repositories using e2e can use it with just the parameter change in their pipelinerun.
It may take time to do clean work.

**Comment by subodh101** [comment]
I would like to use just the py-lint step and not the copy-artifacts.

Under working directory testing/py/
```
pylint kubeflow(module argument) --fail-under=10(argument)  --rcfile=../.pylintrc(argument)
```

If we specify fail-under then the program exits with error as mentioned in the docs.

```
    --fail-under=<score>
                        Specify a score threshold to be exceeded before
                        program exits with error. [current: 10.0]
```

The fail-under parameter is only available after version 2.5.0
I would like to create a new image with pylint ==2.6.0 version. Current version is very old.
https://github.com/kubeflow/testing/blob/9477d82a44b5735925f1d73413b25b74c7cc6c86/images/Pipfile#L37

Question: if I only update the version and merge. Does it make the build and push to the gcr?

**Comment by jlewi** [comment]
> I would like to use just the py-lint step and not the copy-artifacts.

Why do you want to get rid of the copy-artifacts step? The copy-artifacts step uploads the junit.xml files to GCS which is how test failures are reported and show up in spyglass

This is the spyglass uI
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_testing/792/kubeflow-testing-presubmit/1325123085677891584/

The junit files cause test results to be reported in the JUnit tab. 



> Question: if I only update the version and merge. Does it make the build and push to the gcr?

No we currently don't autobuild the images.  They have to be built manually.

We could set that up e.g. using
https://github.com/kubeflow/testing/tree/master/apps-cd

**Comment by subodh101** [comment]
> Why do you want to get rid of the copy-artifacts step?

I thought it is just an extra step.

We are deviating from what we want.
- pylint -> success/failure

Current situation
- pylint via pytest -> xml sent to gcs -> upload from gcs -> parse ->  success/failure

For the logs to show up.
I am thinking of showing it on prow by making changes in https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py such that it not only checks for the job status but also reports by fetching logs in case of failure.

**Comment by subodh101** [comment]
Direct logs of pylint would be much easier to understand because that’s how a user sees them in case of locally running pylint. It also simplifies our process as well as we can just use a light weight image `python:3.9-slim` with latest pylint install in it.

**Comment by jlewi** [comment]
@subodh101 sorry for the slow reply.  I'm not sure how what you are proposing would play well with prow.

Some background:

* Our prow jobs can launch multiple Tekton workflows
* Each Tekton workflow can run multiple tests (e.g. pylint, and pyunittest)
* pyunittest can in turn consist of multiple tests.

So when a user looks at SpyGlass [example](http://8069b97e-prow-prow-6530-1439048706.us-west-2.elb.amazonaws.com/view/s3/aws-kubernetes-jenkins/pr-logs/pull/kubeflow_manifests/1671/kubeflow-manifests-presubmit-e2e/1329736995559182336)
we want the junit page to show a list of all the tests and their status and ideally error messages and logs.

The way that Prow gets that information is from junit.xml files that are stored in GCS. 

So we need some way to produce these junit files and then upload them to GCS. The current pattern is

* Use pytest to emit junit files
* Run copy-artifacts to upload them to GCS.

> Direct logs of pylint 

How are you planning on surfacing the logs? If you don't produce a JUnit xml file how will you surface in spyglass that lint was one of the tests that filed?

> pylint via pytest -> xml sent to gcs -> upload from gcs -> parse -> success/failure

The reason we parse all the xml files in run_e2e_workflow.py is because of how prow works.

We want repo to report a failure to GitHub if any of the tests failed. Prow determines success/failure based on the exit code of the prow job (run_e2e_workflow.py). 

So we have M workflows each running K tests and we need to see if any of them failed. We do this by looking at all of the JUnit XML files and returning non-zero exit status if any failed.
