### ISSUE TITLE
Optional-Test-Infra beta development list

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/testing#785]
Below list is the development list of AWS CI beta stage.

1.~~Migrate from ksonnet-based Argo Workflow to Tekton https://github.com/kubeflow/testing/issues/786~~
   - To migrate to Tekton, we need to install / configure Tekton on Shared Test-infra
3. ~~Provide uniform scripts and enforce WG to use scripts, sacrifice some flexibility to obtain better availability / management. https://github.com/kubeflow/testing/issues/787~~
4. ~~Research release infra, which is CD pipeline. https://github.com/kubeflow/testing/issues/788~~
   - Testing Image CD
5. ~~Divide test-infra into Production and Development environment, every change need to be tested on development env first, then deploy to production. https://github.com/kubeflow/testing/issues/789~~ [Deleted]
6. ~~Automate Webhook Management https://github.com/kubeflow/internal-acls/issues/354~~
7. ~~Existing kfctl + manifests are expensive and flaky, need to be more modular and stable https://github.com/kubeflow/manifests/issues/1613~~
8. ~~IAM as Code https://github.com/kubeflow/testing/issues/848~~
9. ~~Generating Kubeflow + Kubernetes Compatibility Matrix https://github.com/kubeflow/testing/issues/790~~
10. ~~Expose Shared Test-infra configuration https://github.com/kubeflow/testing/issues/791~~
11. ~~Upgrade testing image dependencies kubeflow/testing#779~~
12. ~~Two bots screaming in the same PR if user calls /retest https://github.com/kubernetes/test-infra/pull/19872~~
13. ~~Add documentation to onboard WG on optional-test-infra~~
14. ~~FullCD PR Sender: https://github.com/kubeflow/testing/issues/856~~

**Comment by Bobgy** [comment]
Thanks for driving this!

**Comment by PatrickXYS** [comment]
After migration, let's close this issue and move forward with other optimizations instead
