### ISSUE TITLE
Tekton Pipeline Issue

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/testing#807]
In this [PR](https://github.com/kubeflow/testing/pull/806), I discovered this tekton issue
```
ERROR|2020-11-12T17:45:26|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|46| KeyError: 'status'
Traceback (most recent call last):
  File "/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py", line 41, in log_status
    workflow["status"]["conditions"][0]["reason"])
KeyError: 'status'
INFO|2020-11-12T17:45:26|/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py|88| Retry on exception: 'status'; stack trace:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/src/kubeflow/testing/py/kubeflow/testing/tekton_client.py", line 119, in get_namespaced_custom_object_with_retries
    condition = result["status"]["conditions"][0]["reason"]
KeyError: 'status'
```

@subodh101 Can you help on this? I'm not sure if any of tekton code change caused the issue. 

Given this situation, I'll soon jump in and trying to help us avoid being block.

**Comment by subodh101** [comment]
Yes, you are right. It is not because of any tekton code change.
A similar issue happened when pipelinerun was not able to schedule its job.
https://github.com/kubeflow/gcp-blueprints/issues/143

**Comment by PatrickXYS** [comment]
Seems like we have to get google folks to access into cluster to check what happened

/cc @Bobgy

**Comment by PatrickXYS** [comment]
@subodh101 Can you help lgtm on this PR? https://github.com/kubeflow/kfctl/pull/443

I need to disable the status check to avoid periodic tests failure

**Comment by PatrickXYS** [comment]
Weird, the tests passed again, I will be thinking about Tekton Pipeline and ArgoCD afterwards. 

Looks like this issue happened frequently, which is not desirable
