### ISSUE TITLE
Write metadata to gubernator at start of run.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#82]
In Gubernator, we display metadata that has links to the Argo workflows.

This metadata is stored in finished.json
https://github.com/kubernetes/test-infra/tree/master/gubernator

We currently write finsihed.json after the test finishes. But this means the handy links to the Argo workflows aren't available until the job finishes.

I wonder if we could wrote finished.json at the start of the test but with just the metadata field (no timestamp or result)  and then just overwrite it at the end. The purpose being to display the Argo links even before the job finishes.

@BenTheElder @krzyzacy Do you know if this will work?

**Comment by krzyzacy** [comment]
I think that can work, or we can grab fields from start.json?

**Comment by jlewi** [comment]
The docs don't list metadata as one of the respected fields in start.json
https://github.com/kubeflow/testing/issues/82#issuecomment-376603079

But that would be useful IMO.

**Comment by jlewi** [comment]
I chatted with prow team. It looks like gubernator will fetch metadata from started.json or finished.json depending on which files exist. 

So we just need to write the information to both files.
