### ISSUE TITLE
Image Scanning 

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/testing#847]
This is a reminder to all working groups to setup image scanning during their CI/CD process.  

### AutoML
@andreyvelich, @gaocegege, @johnugeorge

### Deployment
@PatrickXYS, @animeshsingh, @mameshini, @vpavlin, @yanniszark 

### Manifests
@PatrickXYS, @vkoukis, @yanniszark 

### Notebooks
@StefanoFioravanzo,@elikatsis, @kimwnasptd, @thesuperzapper, @yanniszark 

### Pipelines
@james-jwu, @kramachandran, @paveldournov 

### Serving
@animeshsingh, @cliveseldon, @ellistarn, @rakelkar, @yuzisun 

### Training
@gaocegege, @johnugeorge, @terrytangyuan,

**Comment by jtfogarty** [comment]
Duplicate

**Comment by thesuperzapper** [comment]
leaving a link to the duplicate: https://github.com/kubeflow/testing/issues/846
