### ISSUE TITLE
Cron job to garbage collect test resources

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#87]
Our tests create a bunch of resources
- Argo workflows
- Namespaces
- GCE VMs
- GKE clusters

Most of these resources (exception is Argo) should be GC'd by the teardown steps in our tests. But some failures/bugs prevent resources from being GC'd.

It would be good to have a cron job to periodically garbage collect old resources like namespaces.

**Comment by ankushagarwal** [comment]
`/mnt/test-data-volume` also needs GC. It ran out of space yesterday.

**Comment by lluunn** [comment]
We have >1000 workloads in the cluster.

![screenshot from 2018-05-11 14-07-06](https://user-images.githubusercontent.com/32310205/39946866-b96e9d36-5524-11e8-8e3f-f9312c442ef1.png)

**Comment by jlewi** [comment]
There is a proposal in the community to add a TTL field to K8s jobs
kubernetes/kubernetes#64470
Design doc: https://goo.gl/YxtxTi.

Hopefully this will be generalized to Argo workflows.
