### ISSUE TITLE
Go license tools no longer returning licenses for k8s libraries like apimachinery, controller-runtime, etc

### ISSUE THREAD

**Issue by axsaucedo** [kubeflow/testing#887]
Until recently the license tools had worked as expected for the license fetches in our repo, but recently we have seen that in the resulting licenses all the kubernetes licenses as well as several others are no longer being fetched.

The packages fail with the following error:
```
[failed] #x-projnav should occur exactly once, but 0 found for k8s.io/api
Traceback (most recent call last):
  File "/home/alejandro/miniconda3/lib/python3.7/site-packages/get_github_repo.py", line 187, in main
    repo = get_github_repo_for_dep(dep)
  File "/home/alejandro/miniconda3/lib/python3.7/site-packages/get_github_repo.py", line 157, in get_github_repo_for_dep
    repo = fetch_github_uri_from_godoc(dep)
  File "/home/alejandro/miniconda3/lib/python3.7/site-packages/get_github_repo.py", line 107, in fetch_github_uri_from_godoc
    '#x-projnav should occur exactly once, but {} found for {}'.format(len(navs), url))
Exception: #x-projnav should occur exactly once, but 0 found for k8s.io/ap
```

Has there been anything that changed which resulted in this issues? Before the kubernetes libraries in particularly were fetched

Furthermore are there ways to address these issues?

Edit: This is the license tool used in the context above https://github.com/kubeflow/testing/tree/master/py/kubeflow/testing/go-license-tools

**Comment by PatrickXYS** [comment]
@axsaucedo Can you elaborate a bit? 

Which license tool do you refer to? 

/cc @Bobgy

**Comment by axsaucedo** [comment]
@PatrickXYS for sure, this license tools: https://github.com/kubeflow/testing/tree/master/py/kubeflow/testing/go-license-tools

**Comment by axsaucedo** [comment]
I believe this is the tool used to extract the licenses which is the legal requirement when updating the Kubeflow marketplace offering (as all the licenses have to be provided), so I assumed that this would also be an issue in the kubeflow release process

**Comment by axsaucedo** [comment]
Thanks, let me know if you need further details
