### ISSUE TITLE
Let optional test infra manage kubeflow/testing presubmit/postsubmit

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/testing#919]
/assign @PatrickXYS 

As discussed, adding this issue as a tracker.

I'll go ahead and remove test triggers on k8s prow for this repo.

**Comment by PatrickXYS** [comment]
@Bobgy Thanks for bringing this up, after removing it from k8s prow, I'll make sure to add it into optional-test-infra.

**Comment by Bobgy** [comment]
Note, it's already removed from k8s prow

**Comment by PatrickXYS** [comment]
Thanks @Bobgy  I'll be working on migrating to optional-test-infra a bit later, kind of busy at this moment

**Comment by Bobgy** [comment]
No worry, do so on your own pace
