### ISSUE TITLE
rebuild test-worker image

### ISSUE THREAD

**Issue by theofpa** [kubeflow/testing#932]
we need to rebuild the test-worker image to be able to launch ephemeral k8s clusters >1.19
```
(base) theofpa@z420:~$ docker run --entrypoint /usr/local/bin/eksctl public.ecr.aws/j1r0q0g6/kubeflow-testing:latest version
0.30.0
```

to fix kubeflow/kfserving#1482

**Comment by PatrickXYS** [comment]
/assign

@theofpa Sounds good, I can find time working on this next Monday

**Comment by PatrickXYS** [comment]
Finished rebuilding the image, it's available with latest tag.

Please reopen if there's another issue

**Comment by theofpa** [comment]
@PatrickXYS thank you!
